# build stage
FROM node:22 AS build-stage
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

# production stage
FROM node:22-alpine AS production-stage
WORKDIR /app
COPY --from=build-stage /app/dist ./dist
RUN yarn global add serve

EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]