FROM node:24-bookworm-slim

WORKDIR /usr/app

# Enable Corepack
RUN corepack enable

# Copy only what's needed for dependency install
COPY package.json yarn.lock .yarnrc.yml ./

# Run corepack and yarn install
RUN corepack install && yarn install --immutable

# App/config files
COPY . .

EXPOSE 3000
CMD ["yarn", "dev", "--host"]