FROM node:24

WORKDIR /usr/app

# Enable Corepack
RUN corepack enable
ENV CHOKIDAR_USEPOLLING=1
ENV WATCHPACK_POLLING=true

# Copy only what's needed for dependency install
COPY package.json yarn.lock .yarnrc.yml ./

# Run corepack and yarn install
RUN corepack install && yarn install --immutable

# App/config files
COPY . .

EXPOSE 3000
CMD ["yarn", "dev", "--host"]