SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `addresses`;
TRUNCATE TABLE `answers`;
TRUNCATE TABLE `authorities`;
TRUNCATE TABLE `blogs`;
TRUNCATE TABLE `board_documents`;
TRUNCATE TABLE `board_members`;
TRUNCATE TABLE `boards`;
TRUNCATE TABLE `committee_members`;
TRUNCATE TABLE `committees`;
TRUNCATE TABLE `contribution_periods`;
TRUNCATE TABLE `contributions`;
TRUNCATE TABLE `event_feedback`;
TRUNCATE TABLE `event_pictures`;
TRUNCATE TABLE `event_signups`;
TRUNCATE TABLE `event_sign_up_answers`;
TRUNCATE TABLE `events`;
TRUNCATE TABLE `files`;
TRUNCATE TABLE `guests`;
TRUNCATE TABLE `memberships`;
TRUNCATE TABLE `news`;
TRUNCATE TABLE `questions`;
TRUNCATE TABLE `redirects`;
TRUNCATE TABLE `sponsors`;
TRUNCATE TABLE `surveys`;
TRUNCATE TABLE `telemetries`;
TRUNCATE TABLE `users`;

SET FOREIGN_KEY_CHECKS = 1;
