services:
#  frontend:
#    build:
#      context: ./blueshell-frontend
#      dockerfile: Dockerfile-dev
#    ports:
#      - "3000:3000"
#    volumes:
#      - "./blueshell-frontend:/usr/app:rw"
#      - "/usr/app/node_modules"
#    depends_on:
#      - api
#    networks:
#      - global_network

  api:
    build:
      context: ./blueshell-api
      dockerfile: Dockerfile-dev
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - "./blueshell-api:/usr/app:rw"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/blueshell?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: blueshell
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080/api/contributionPeriods" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - global_network
    restart: unless-stopped
    env_file:
      - Docker/env/.db.env

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - "./data:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - global_network
    restart: unless-stopped
    env_file:
      - Docker/env/.db.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.0.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - global_network
    restart: unless-stopped
    env_file:
      - Docker/env/.rabbitmq.env
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl status || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  apigateway:
    build:
      context: .
      dockerfile: ./APIGateway/Dockerfile
      args:
        - PORT=1024
    ports:
      - "1024:80"
      - "5005:5005"
    networks:
      - global_network
    depends_on:
      - rabbitmq
      - blogservice
      - emailparser
      - eventparser
      - fileservice
      - telemetry
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 5
    image: apigateway:latest
    restart: unless-stopped
    env_file:
      - Docker/env/.app.env
      - Docker/env/.rabbitmq.env
  blogservice:
    build:
      context: .
      dockerfile: ./BlogService/Dockerfile
      args:
        - PORT=8081
    ports:
      - "5006:5005"
    networks:
      - global_network
    depends_on:
      - rabbitmq
      - db
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    env_file:
      - Docker/env/.db.env
      - Docker/env/.app.env
      - Docker/env/.rabbitmq.env
    image: blogservice:latest
  emailparser:
    build:
      context: .
      dockerfile: ./EmailParser/Dockerfile
      args:
        - PORT=8082
    ports:
      - "5007:5005"
    networks:
      - global_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
    image: emailparser:latest
    restart: unless-stopped
    env_file:
      - Docker/env/.app.env
      - Docker/env/.rabbitmq.env
  eventparser:
    build:
      context: .
      dockerfile: ./EventParser/Dockerfile
      args:
        - PORT=8083
    ports:
      - "5008:5005"
    networks:
      - global_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
    image: eventparser:latest
    restart: unless-stopped
    env_file:
      - Docker/env/.app.env
      - Docker/env/.rabbitmq.env
  fileservice:
    build:
      context: .
      dockerfile: ./FileService/Dockerfile
      args:
        - PORT=8086
    ports:
      - "5011:5005"
    networks:
      - global_network
    depends_on:
      - rabbitmq
      - db
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
    image: fileservice:latest
    volumes:
      - "./files:/app/files"
    restart: unless-stopped
    env_file:
      - Docker/env/.db.env
      - Docker/env/.app.env
      - Docker/env/.rabbitmq.env
  socialmediaservice:
    build:
      context: .
      dockerfile: ./SocialMediaService/Dockerfile
      args:
        - PORT=8084
    ports:
      - "5009:5005"
    networks:
      - global_network
    depends_on:
      - rabbitmq
      - apigateway
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
    image: socialmediaservice:latest
    restart: unless-stopped
    env_file:
      - Docker/env/.app.env
      - Docker/env/.rabbitmq.env
  telemetry:
    build:
      context: .
      dockerfile: ./Telemetry/Dockerfile
      args:
        - PORT=8085
    ports:
      - "5010:5005"
    networks:
      - global_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
    image: telemetry:latest
    restart: unless-stopped
    env_file:
      - Docker/env/.db.env
      - Docker/env/.app.env
      - Docker/env/.rabbitmq.env
networks:
  global_network:
    driver: bridge