services:
  db:
    image: mariadb:10.11.10
    container_name: db
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql
      - "./env/0_init.sql:/docker-entrypoint-initdb.d/0_init.sql"
      - "./env/1_dump.sql:/docker-entrypoint-initdb.d/1_dump.sql"
    networks:
      - global_network
    restart: unless-stopped
    env_file:
      - ./env/.db.env
    environment:
      - TZ=Europe/Amsterdam
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  frontend:
    image: frontend:dev
    pull_policy: never
    build:
      context: frontend
      dockerfile: Dockerfile-dev
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/usr/app"
      - ./openapi:/usr/openapi
      - /usr/app/.yarn
    networks:
      - global_network
    environment:
      - TZ=Europe/Amsterdam
      - VITE_APP_URL=http://localhost:8080
    depends_on:
      - api
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  api:
    image: api:dev
    pull_policy: never
    build:
      context: api
      dockerfile: Dockerfile-dev
      additional_contexts:
        root: .
    volumes:
      - ./api:/app
      - maven-repo:/root/.m2
      - ./openapi:/openapi
      - ./storage:/home/storage
    ports:
      - "8080:8080"
    networks:
      - global_network
    env_file:
      - ./env/.api.env
    environment:
      - TZ=Europe/Amsterdam
      - APP_URL=http://localhost:8080
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  global_network:
    driver: bridge

volumes:
  data:
  maven-repo:
  nginx_certs:
    driver: local
