services:
  db:
    image: mariadb:10.11.10
    container_name: db
    networks:
      - database
    volumes:
      - db_data:/var/lib/mysql
      - "./env/0_init.sql:/docker-entrypoint-initdb.d/0_init.sql"
      - "./env/1_dump.sql:/docker-entrypoint-initdb.d/1_dump.sql"
    env_file:
      - ./env/.db.env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  api:
    image: ghcr.io/esa-blueshell/api:latest
    pull_policy: always
    build:
      context: .
      dockerfile:
        api/Dockerfile
    restart: unless-stopped
    env_file:
      - ./env/.api.env
    environment:
      - TZ=Europe/Amsterdam
      - APP_URL=https://esa-blueshell.nl/api
      - FRONTEND_URL=https://esa-blueshell.nl
    volumes:
      - "./storage:/home/storage"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - frontback
      - database
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  frontend:
    image: ghcr.io/esa-blueshell/frontend:latest
    pull_policy: always
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      api:
        condition: service_healthy
    networks:
      - frontback
    environment:
      - TZ=Europe/Amsterdam
      - VITE_APP_URL=https://esa-blueshell.nl/api
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontback
    depends_on:
      frontend:
        condition: service_healthy
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-www:/var/www/certbot

networks:
  frontback:
  database:

volumes:
  letsencrypt:
  certbot-www:
  db_data: