services:
  apigateway:
    build:
      context: .
      dockerfile: ./APIGateway/Dockerfile
      args:
        - PORT=80
    ports:
      - "80:80"
      - "5005:5005"
    networks:
      - global_network
    depends_on:
      - blogservice
      - emailparser
      - eventparser
      - socialmediaservice
      - telemetry
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 5
  blogservice:
    build:
      context: .
      dockerfile: ./BlogService/Dockerfile
      args:
        - PORT=8081
    ports:
      - "5006:5005"
    networks:
      - global_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
  emailparser:
    build:
      context: .
      dockerfile: ./EmailParser/Dockerfile
      args:
        - PORT=8082
    ports:
      - "5007:5005"
    networks:
      - global_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
  eventparser:
    build:
      context: .
      dockerfile: ./EventParser/Dockerfile
      args:
        - PORT=8083
    ports:
      - "5008:5005"
    networks:
      - global_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
  socialmediaservice:
    build:
      context: .
      dockerfile: ./SocialMediaService/Dockerfile
      args:
        - PORT=8084
    ports:
      - "5009:5005"
    networks:
      - global_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
  telemetry:
    build:
      context: .
      dockerfile: ./Telemetry/Dockerfile
      args:
        - PORT=8085
    ports:
      - "5010:5005"
    networks:
      - global_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  global_network:
    driver: bridge