services:
  db:
    image: mariadb:10.11.10
    container_name: db
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql
      - "./env/0_init.sql:/docker-entrypoint-initdb.d/0_init.sql"
      - "./env/1_dump.sql:/docker-entrypoint-initdb.d/1_dump.sql"
    networks:
      - global_network
    restart: unless-stopped
    env_file:
      - ./env/.db.env
    environment:
      - TZ=Europe/Amsterdam
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - global_network
    env_file:
      - ./env/.rabbitmq.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  frontend:
    image: frontend:dev
    pull_policy: never
    build:
      context: frontend
      dockerfile: Dockerfile-dev
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/usr/app"
      - ./openapi:/usr/openapi
      - /usr/app/.yarn
    networks:
      - global_network
    environment:
      - TZ=Europe/Amsterdam
      - VITE_APP_URL=http://localhost:8080
      - VITE_COVERAGE=${VITE_COVERAGE:-false}
    depends_on:
      - api
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  api:
    image: api:dev
    pull_policy: never
    build:
      context: .
      dockerfile: api/Dockerfile-dev
    volumes:
      - ./:/app
      - ./storage:/home/storage
      - gradle-cache:/root/.gradle
      - playwright-browsers:/ms-playwright
      - playwright-browsers:/root/.cache/ms-playwright
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - global_network
    env_file:
      - ./env/.api.env
      - ./env/.db.env
    environment:
      - TZ=Europe/Amsterdam
      - APP_URL=http://localhost:8080
      - FRONTEND_URL=http://localhost:3000
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    depends_on:
      - db
      - rabbitmq
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 30s

networks:
  global_network:
    driver: bridge

volumes:
  data:
  gradle-cache:
  playwright-browsers:
  nginx_certs:
    driver: local
