openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://172.18.0.10:8080/event-parser
  description: Generated server url
paths:
  /parse:
    post:
      tags:
      - event-parser-controller
      operationId: parseEvent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SocialDTO'
  /health:
    get:
      tags:
      - main-controller
      operationId: healthCheck
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: boolean
components:
  schemas:
    CommitteeDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
    EventDTO:
      type: object
      properties:
        banner:
          $ref: '#/components/schemas/FileDTO'
        id:
          type: integer
          format: int64
        committeeId:
          type: integer
          format: int64
        committee:
          $ref: '#/components/schemas/CommitteeDTO'
        title:
          type: string
          maxLength: 200
          minLength: 0
        description:
          type: string
          minLength: 1
        location:
          type: string
        startTime:
          type: string
          minLength: 1
        endTime:
          type: string
          minLength: 1
        memberPrice:
          type: string
        publicPrice:
          type: string
        visible:
          type: boolean
        membersOnly:
          type: boolean
        signUp:
          type: boolean
        signUpForm:
          type: array
          items:
            $ref: '#/components/schemas/SignUpFormDTO'
    FileDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        url:
          type: string
        uploaderId:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        mediaType:
          type: string
        size:
          type: integer
          format: int64
        fileName:
          type: string
        fileType:
          type: string
          enum:
          - DOCUMENT
          - SIGNATURE
          - PROFILE_PICTURE
          - EVENT_BANNER
          - EVENT_PICTURE
          - SPONSOR_PICTURE
        base64Content:
          type: string
    SignUpFormDTO:
      type: object
      properties:
        prompt:
          type: string
          minLength: 1
        type:
          type: string
          minLength: 1
        options:
          type: array
          items:
            type: string
            minLength: 1
    SocialDTO:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        text:
          type: string
        url:
          type: string
        platforms:
          type: array
          items:
            type: string
            enum:
            - FACEBOOK
            - LINKEDIN
            - TWITTER
            - INSTAGRAM
