CREATE DATABASE IF NOT EXISTS BlogService;
CREATE DATABASE IF NOT EXISTS FileService;
CREATE DATABASE IF NOT EXISTS SocialMediaService;
CREATE DATABASE IF NOT EXISTS TelemetryService;
CREATE DATABASE IF NOT EXISTS API;