apiVersion: v1
data:
  APP_URL: localhost:3000
  FRONTEND_URL: '"http://localhost:3000"'
  JWT_SECRET: '"YourBase64Encoded64ByteKeyHerejlasjdlfkjasdfjlakw4jpoiasdvpocimu4019mcfawb09hmf8j123890cqwepjc"'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: app-env
