server:
  port: 8080

blueshell:
  identity:
    enabled: true

spring:
  main:
    web-application-type: reactive

  application:
    name: ApiGateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-route
          uri: lb://API
          predicates:
            - Path=/download/**,/eventPictures/**,/events/**,/memberships/**,/users/**,/auth/**,/contributionPeriods/**,/contributions/**,/sponsors/**,/committees/**

        - id: blog-parser-route
          uri: lb://BlogParser
          predicates:
            - Path=/blog-parser/**

        - id: blog-service-route
          uri: lb://BlogService
          predicates:
            - Path=/blogs/**

        - id: email-parser-route
          uri: lb://EmailParser
          predicates:
            - Path=/email

        - id: event-parser-route
          uri: lb://EventParser
          predicates:
            - Path=/event-parser/**

        - id: file-service-route
          uri: lb://FileService
          predicates:
            - Path=/files/**

        - id: telemetry-service-route
          uri: lb://TelemetryService
          predicates:
            - Path=/telemetry/**

        - id: telemetry-ws-route
          uri: lb:ws://TelemetryService
          predicates:
            - Path=/telemetry/ws/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    urls:
      - name: API Gateway
        url: /v3/api-docs

      - name: API Service
        url: /api/v3/api-docs

      - name: Blog Parser Service
        url: /blog-parser/v3/api-docs

      - name: Blog Service
        url: /blogs/v3/api-docs

      - name: Email Parser Service
        url: /email-parser/v3/api-docs

      - name: Event Parser Service
        url: /event-parser/v3/api-docs

      - name: File Service
        url: /files/v3/api-docs

      - name: Social Media Service
        url: /social-media/v3/api-docs

      - name: Telemetry Service
        url: /telemetry/v3/api-docs