spring:
  jpa:
    show-sql: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    org.springframework.security: error
    org.springframework.expression: error
    org.springframework.web: debug