spring:
  application:
    db: blueshell-test

  main:
    banner-mode: off
    log-startup-info: false

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

  rabbitmq:
    listener:
      simple:
        auto-startup: false
      direct:
        auto-startup: false

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  level:
    root: INFO

    net.blueshell: INFO
    net.blueshell.api: DEBUG

    org.springframework: WARN
    org.springframework.web: WARN
    org.springframework.boot.autoconfigure: WARN
    org.springframework.jdbc: WARN
    org.springframework.security: WARN

    # Server (Tomcat/Undertow/Jetty)
    org.apache.catalina: WARN
    org.apache.coyote: WARN
    org.apache.tomcat: WARN

    # DB / ORM
    org.hibernate: WARN
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.type.descriptor.jdbc: OFF
    org.hibernate.orm.jdbc.bind: OFF
    com.zaxxer.hikari: WARN
    org.flywaydb: WARN

    # If you use Testcontainers
    org.testcontainers: WARN
    com.github.dockerjava: WARN

app:
  jobs:
    max-retries: 3
    initial-backoff-millis: 1
    backoff-multiplier: 2.0

security:
  auth-rate-limit:
    enabled: false
