spring:
  application:
    db: blueshell-test


  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: INFO
    com.zaxxer.hikari: DEBUG
    org.flywaydb: DEBUG