
spring:
  main:
    web-application-type: servlet

  application:
    name: BlueshellAPI
    db: blueshell

  datasource:
    host: ${MYSQL_HOST}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${spring.datasource.host}:${MYSQL_PORT}/${spring.application.db}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: "SELECT 1"
      keepalive-time: 6000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
      hibernate.connection.characterEncoding: utf8mb4
      hibernate.connection.useUnicode: true
      hibernate.connection.useSSL: false
      hibernate.connection.serverTimezone: UTC
      hibernate.connection.allowPublicKeyRetrieval: true
      hibernate.connection.collation: utf8mb4_unicode_ci

  flyway:
    enabled: true
    locations: classpath:db/migration

  mvc:
    dispatch-options-request: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: Blueshell API
    description: The API for the Blueshell Esports website
    version: 1.0.0

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000

frontend:
  url: ${FRONTEND_URL}

storage:
  location: ${STORAGE_LOCATION}

mollie:
  apiKey: ${MOLLIE_API_KEY}

brevo:
  apiKey: ${BREVO_API_KEY}
  templates:
    userActivationId: ${BREVO_TEMPLATE_USER_ACTIVATION_ID}
    memberActivationId: ${BREVO_TEMPLATE_MEMBER_ACTIVATION_ID}
    eventSignupId: ${BREVO_TEMPLATE_EVENT_SIGNUP_ID}
    passwordResetId: ${BREVO_TEMPLATE_PASSWORD_RESET_ID}
    contributionId: ${BREVO_TEMPLATE_CONTRIBUTION_ID}
    contributionReminderId: ${BREVO_TEMPLATE_CONTRIBUTION_REMINDER_ID}
  folders:
    contributionPeriodsId: ${BREVO_FOLDER_CONTRIBUTION_PERIODS_ID}

google:
  calendar:
    id: ${GOOGLE_CALENDAR_ID}
    clientId: ${GOOGLE_CALENDAR_CLIENT_ID}
    clientEmail: ${GOOGLE_CALENDAR_CLIENT_EMAIL}
    privateKeyPkcs8: ${GOOGLE_CALENDAR_PRIVATE_KEY_PKCS8}
    privateKeyId: ${GOOGLE_CALENDAR_PRIVATE_KEY_ID}

facebook:
  page:
    id: ${FACEBOOK_PAGE_ID}
  access:
    token: ${FACEBOOK_ACCESS_TOKEN}

x:
  api:
    key: ${X_API_KEY}
    secret: ${X_API_SECRET}
  access:
    token: ${X_ACCESS_TOKEN}
    secret: ${X_ACCESS_SECRET}