name: Setup Node & Yarn (Corepack)
description: Install Node with actions/setup-node and activate Yarn via Corepack
inputs:
  node-version:
    description: Node.js version (e.g. "24")
    required: true
  yarn-version:
    description: Yarn version (e.g. "4.9.4")
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache-dependency-path: |
          'services/frontend/yarn.lock'
          'services/frontend/.yarnrc.yml'

    - name: Enable Yarn via Corepack
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        corepack enable
        corepack prepare yarn@${{ inputs.yarn-version }} --activate
        echo "Yarn $(yarn --version) activated"

    - name: Restore Yarn cache
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          services/frontend/.yarn/cache
          services/frontend/.yarn/unplugged
          services/frontend/.yarn/install-state.gz
          services/frontend/.pnp.*
          services/frontend/node_modules
        key: ${{ runner.os }}-node${{ inputs.node-version }}-yarn${{ inputs.yarn-version }}-${{ hashFiles('services/frontend/yarn.lock', 'services/frontend/.yarnrc.yml') }}


    - name: Install dependencies
      shell: bash
      working-directory: services/frontend
      run: yarn install --immutable
