CREATE TABLE email_suppressions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    reason ENUM('HARD_BOUNCE', 'COMPLAINT', 'SOFT_BOUNCE_THRESHOLD') NOT NULL,
    first_seen_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    last_seen_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    bounce_count INT NOT NULL DEFAULT 1,
    UNIQUE INDEX idx_suppression_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
