services:
  db:
    image: mariadb:10.11.10
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - "./data:/var/lib/mysql"
      - "./env/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks: [ global_network ]
    restart: unless-stopped
    env_file:
      - env/.db.env
    command: --log-bin-trust-function-creators=1
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  rabbitmq:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq
    networks: [ global_network ]
    restart: unless-stopped
    env_file:
      - env/.rabbitmq.env
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl status || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  frontend:
    container_name: frontend
    image: frontend:latest
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile-build
    ports:
      - "3000:3000"
    networks: [ global_network ]
    depends_on: [ api-gateway ]
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider",
              "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    build:
      context: ..
      dockerfile: api-gateway/Dockerfile-build
      args: [ PORT=8080 ]
    ports:
      - "8080:8080"
    networks: [ global_network ]
    restart: unless-stopped
    env_file:
      - env/.app.env
      - env/.rabbitmq.env
    depends_on:
      - rabbitmq
      - blog-service
      - email-parser
      - event-parser
      - file-service
      - telemetry-service
      - eureka-server
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider",
              "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  api:
    container_name: api
    image: api:latest
    build:
      context: ..
      dockerfile: api/Dockerfile-build
      args: [ PORT=8080 ]
    networks: [ global_network ]
    restart: unless-stopped
    env_file:
      - env/.db.env
      - env/.rabbitmq.env
      - env/.app.env
    depends_on: [ db, rabbitmq, eureka-server ]
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider",
              "http://localhost:8080/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    build:
      context: ..
      dockerfile: eureka-server/Dockerfile-build
      args: [ PORT=8761 ]
    networks: [ global_network ]
    restart: unless-stopped
    env_file:
      - env/.app.env
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider",
              "http://localhost:8761/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  blog-parser:
    image: blog-parser:latest
    container_name: blog-parser
    build:
      context: ..
      dockerfile: blog-parser/Dockerfile-build
      args: [ PORT=8080 ]
    networks: [ global_network ]
    restart: unless-stopped
    env_file:
      - env/.db.env
      - env/.app.env
      - env/.rabbitmq.env
    depends_on: [ rabbitmq, db, eureka-server ]
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider",
              "http://localhost:8080/blog-parser/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  blog-service:
    image: blog-service:latest
    container_name: blog-service.yaml
    build:
      context: ..
      dockerfile: blog-service/Dockerfile-build
      args: [ PORT=8080 ]
    networks: [ global_network ]
    restart: unless-stopped
    env_file:
      - env/.db.env
      - env/.app.env
      - env/.rabbitmq.env
    depends_on: [ rabbitmq, db, eureka-server ]
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider",
              "http://localhost:8080/blogs/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  email-parser:
    image: email-parser:latest
    container_name: email-parser
    build:
      context: ..
      dockerfile: email-parser/Dockerfile-build
      args: [ PORT=8080 ]
    networks: [ global_network ]
    restart: unless-stopped
    env_file:
      - env/.app.env
      - env/.rabbitmq.env
    depends_on: [ eureka-server, rabbitmq ]
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider",
              "http://localhost:8080/email-parser/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  event-parser:
    image: event-parser:latest
    container_name: event-parser
    build:
      context: ..
      dockerfile: event-parser/Dockerfile-build
      args: [ PORT=8080 ]
    networks: [ global_network ]
    restart: unless-stopped
    env_file:
      - env/.app.env
      - env/.rabbitmq.env
    depends_on: [ eureka-server, rabbitmq ]
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider",
              "http://localhost:8080/event-parser/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  file-service:
    image: file-service:latest
    container_name: file-service.yaml
    build:
      context: ..
      dockerfile: file-service/Dockerfile-build
      args: [ PORT=8080 ]
    volumes:
      - "./files:/app/files"
    networks: [ global_network ]
    restart: unless-stopped
    env_file:
      - env/.db.env
      - env/.app.env
      - env/.rabbitmq.env
    depends_on: [ rabbitmq, db, eureka-server ]
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider",
              "http://localhost:8080/files/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  social-media-service:
    image: social-media-service:latest
    container_name: social-media-service.yaml
    build:
      context: ..
      dockerfile: social-media-service/Dockerfile-build
      args: [ PORT=8080 ]
    networks: [ global_network ]
    restart: unless-stopped
    env_file:
      - env/.app.env
      - env/.rabbitmq.env
    depends_on: [ rabbitmq, api-gateway, eureka-server ]
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider",
              "http://localhost:8080/social-media/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  telemetry-service:
    image: telemetry-service:latest
    container_name: telemetry-service.yaml
    build:
      context: ..
      dockerfile: telemetry-service/Dockerfile-build
      args: [ PORT=8080 ]
    networks: [ global_network ]
    restart: unless-stopped
    env_file:
      - env/.db.env
      - env/.app.env
      - env/.rabbitmq.env
    depends_on: [ eureka-server, rabbitmq ]
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider",
              "http://localhost:8080/telemetry/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  global_network:
    driver: bridge