# Use an official Maven image to build the application
FROM maven:3.9.9-eclipse-temurin-21-alpine AS build-parent

# Set the working directory in the container
WORKDIR /app

# Copy the local Maven files
COPY ./${SERVICE_NAME}/.mvn .mvn
COPY ./${SERVICE_NAME}/mvnw .

# Copy the parent POM and module POMs
COPY ./pom.xml /app/parent/pom.xml
COPY ./Common/pom.xml /app/parent/Common/pom.xml
COPY ./APIGateway/pom.xml /app/parent/APIGateway/pom.xml
COPY ./BlogService/pom.xml /app/parent/BlogService/pom.xml
COPY ./Common/pom.xml /app/parent/Common/pom.xml
COPY ./EmailParser/pom.xml /app/parent/EmailParser/pom.xml
COPY ./EventParser/pom.xml /app/parent/EventParser/pom.xml
COPY ./SocialMediaService/pom.xml /app/parent/SocialMediaService/pom.xml
COPY ./Telemetry/pom.xml /app/parent/Telemetry/pom.xml

# Download dependencies and build the parent project
RUN --mount=type=cache,target=/root/.m2,rw ./mvnw -B install -DskipTests -f ./parent/pom.xml -nsu

# Use an official Maven image to build the Common module
FROM maven:3.9.9-eclipse-temurin-21-alpine AS build-common
WORKDIR /app

# Copy the local Maven files from the previous stage
COPY --from=build-parent /app/.mvn .mvn
COPY --from=build-parent /app/mvnw .

# Copy the Common module
COPY ./Common/pom.xml ./Common/pom.xml
COPY ./Common/src ./Common/src

# Build the Common module
RUN --mount=type=cache,target=/root/.m2,rw ./mvnw -B install -DskipTests -f ./Common/pom.xml -nsu -o

# Use an official Maven image to build the service
FROM maven:3.9.9-eclipse-temurin-21-alpine AS build
WORKDIR /app
ARG SERVICE_NAME
ARG PORT

# Copy the service POM, source code, and local Maven repository
COPY ./${SERVICE_NAME}/pom.xml .
COPY ./${SERVICE_NAME}/src ./src
COPY --from=build-common /app/.mvn .mvn
COPY --from=build-common /app/mvnw .

# Build the service
RUN --mount=type=cache,target=/root/.m2,rw ./mvnw -B install -DskipTests -nsu

# Use an official OpenJDK image to run the application
FROM eclipse-temurin:21-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the built jar file from the build stage
COPY --from=build /app/target/*.jar app.jar

# Expose the port the application runs on
EXPOSE ${PORT} 5005

# Run the application
ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "app.jar"]