# Use an official Maven image to build the application
FROM maven:3.9.9-eclipse-temurin-21-alpine AS build-parent

# Set the working directory in the container
WORKDIR /app

# Copy the local Maven files
COPY ./${SERVICE_NAME}/.mvn .mvn
COPY ./${SERVICE_NAME}/mvnw .

# Copy the parent POM and module POMs
COPY ./pom.xml /app/parent/pom.xml
COPY ./core-commons/pom.xml /app/parent/core-commons/pom.xml
COPY ./db-commons/pom.xml /app/parent/db-commons/pom.xml
COPY ./APIGateway/pom.xml /app/parent/APIGateway/pom.xml
COPY ./BlogService/pom.xml /app/parent/BlogService/pom.xml
COPY ./EmailParser/pom.xml /app/parent/EmailParser/pom.xml
COPY ./EventParser/pom.xml /app/parent/EventParser/pom.xml
COPY ./SocialMediaService/pom.xml /app/parent/SocialMediaService/pom.xml
COPY ./Telemetry/pom.xml /app/parent/Telemetry/pom.xml

# Download dependencies and build the parent project
RUN --mount=type=cache,target=/root/.m2,rw ./mvnw -B install -DskipTests -f ./parent/pom.xml -nsu

# Build core-commons module
FROM maven:3.9.9-eclipse-temurin-21-alpine AS build-common
WORKDIR /app

# Copy Maven files and core-commons code
COPY --from=build-parent /app/.mvn .mvn
COPY --from=build-parent /app/mvnw .
COPY ./core-commons/pom.xml ./core-commons/pom.xml
COPY ./core-commons/src ./core-commons/src

# Install core-commons to Maven cache
RUN --mount=type=cache,target=/root/.m2,rw ./mvnw -B install -DskipTests -f ./core-commons/pom.xml -nsu -o

# Build db-commons module
FROM maven:3.9.9-eclipse-temurin-21-alpine AS build-db-common
WORKDIR /app

# Copy Maven files and db-commons code
COPY --from=build-parent /app/.mvn .mvn
COPY --from=build-parent /app/mvnw .
COPY ./db-commons/pom.xml ./db-commons/pom.xml
COPY ./db-commons/src ./db-commons/src

# Install db-commons to Maven cache
RUN --mount=type=cache,target=/root/.m2,rw ./mvnw -B install -DskipTests -f ./db-commons/pom.xml -nsu -o

# Build the service (depends on core-commons and db-commons)
FROM maven:3.9.9-eclipse-temurin-21-alpine AS build
WORKDIR /app
ARG SERVICE_NAME
ARG PORT

# Copy service code and Maven files
COPY ./${SERVICE_NAME}/pom.xml .
COPY ./${SERVICE_NAME}/src ./src
COPY --from=build-parent /app/.mvn .mvn
COPY --from=build-parent /app/mvnw .

# Build the service (Maven cache includes core-commons and db-commons)
RUN --mount=type=cache,target=/root/.m2,rw ./mvnw -B install -DskipTests -o -nsu

# Runtime stage
FROM eclipse-temurin:21-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE ${PORT} 5005
ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "app.jar"]