export enum FileType {
  DOCUMENT = 'DOCUMENT',
  SIGNATURE = 'SIGNATURE',
  PROFILE_PICTURE = 'PROFILE_PICTURE',
  EVENT_BANNER = 'EVENT_BANNER',
  EVENT_PICTURE = 'EVENT_PICTURE',
  SPONSOR_PICTURE = 'SPONSOR_PICTURE'
}
