import org.flywaydb.core.api.migration.BaseJavaMigration
import net.blueshell.api.validation.user.UniqueUser
import net.blueshell.api.validation.group.Administration
import net.blueshell.api.dto.PersonalInfoDTO
import net.blueshell.api.dto.user.SimpleUserDTO
import net.blueshell.api.base.BaseDTO
import net.blueshell.api.dto.error.FieldValidationErrorDTO
import net.blueshell.api.dto.event.EventBannerDTO
import net.blueshell.api.dto.survey.SurveyDTO
import net.blueshell.api.dto.FileDTO
import net.blueshell.api.validation.event.ValidEventSignUp
import net.blueshell.api.validation.event.GuestOrUserRequired
import net.blueshell.api.dto.survey.AnswerDTO
import net.blueshell.api.dto.GuestDTO
import net.blueshell.api.validation.survey.ValidAnswer
import net.blueshell.api.validation.survey.ValidQuestionList
import net.blueshell.api.dto.survey.QuestionDTO
import net.blueshell.api.validation.survey.ValidQuestion
import net.blueshell.api.common.enums.QuestionType
import net.blueshell.api.validation.user.UniqueUsername
import net.blueshell.api.dto.committee.CommitteeMemberDTO
import net.blueshell.api.validation.address.ValidCountryCode
import net.blueshell.api.dto.TelemetryDTO
import net.blueshell.api.validation.membership.NoExistingMembershipForUserId
import net.blueshell.api.common.enums.MemberType
import net.blueshell.api.validation.date.Today
import net.blueshell.api.validation.user.ValidMobilePhoneNumber
import net.blueshell.api.service.email.EmailService
import net.blueshell.api.job.email.RecoveryEmailJob
import org.springframework.retry.annotation.Recover
import net.blueshell.api.job.email.EventSignupEmailJob
import net.blueshell.api.job.email.ContributionReminderEmailJob
import net.blueshell.api.service.ContactService
import net.blueshell.api.service.UserService
import net.blueshell.api.job.contact.SyncContactJob
import org.springframework.web.client.RestClientResponseException
import net.blueshell.api.service.contribution.ContributionPeriodService
import net.blueshell.api.job.contact.AddContactToListJob
import net.blueshell.api.model.contribution.ContributionPeriod
import net.blueshell.api.job.contact.RemoveContactFromListJob
import net.blueshell.api.job.contact.CreateContributionPeriodListJob
import net.blueshell.api.service.CalendarService
import net.blueshell.api.service.event.EventService
import net.blueshell.api.job.calendar.AddEventToCalendarJob
import net.blueshell.api.job.calendar.SyncEventToCalendarJob
import net.blueshell.api.job.calendar.UpdateEventInCalendarJob
import net.blueshell.api.job.calendar.RemoveEventFromCalendarJob
import org.springframework.security.core.context.SecurityContextHolder
import org.springframework.security.core.GrantedAuthority
import io.jsonwebtoken.Claims
import io.jsonwebtoken.Jwts
import org.springframework.security.core.userdetails.UserDetails
import io.jsonwebtoken.io.Decoders
import net.blueshell.api.auth.JwtTokenUtil
import org.springframework.security.core.userdetails.UserDetailsService
import org.springframework.web.filter.OncePerRequestFilter
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken
import org.springframework.security.web.authentication.WebAuthenticationDetailsSource
import org.springframework.security.web.AuthenticationEntryPoint
import net.blueshell.api.base.EmailContent
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import org.hibernate.annotations.CreationTimestamp
import jakarta.persistence.FetchType
import jakarta.persistence.JoinColumn
import org.hibernate.annotations.UpdateTimestamp
import org.springframework.data.annotation.LastModifiedBy
import org.hibernate.Hibernate
import net.blueshell.api.base.BaseModel
import jakarta.persistence.PrePersist
import net.blueshell.api.base.JpaListener
import net.blueshell.api.common.event.jpa.PrePersistEvent
import jakarta.persistence.PostPersist
import net.blueshell.api.common.event.jpa.PostPersistEvent
import jakarta.persistence.PreUpdate
import jakarta.persistence.PostUpdate
import jakarta.persistence.PreRemove
import net.blueshell.api.common.event.jpa.PreRemoveEvent
import jakarta.persistence.PostRemove
import net.blueshell.api.common.event.jpa.PostRemoveEvent
import org.springframework.context.ApplicationEventPublisher
import org.springframework.data.repository.NoRepositoryBean
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.data.jpa.repository.JpaSpecificationExecutor
import net.blueshell.api.base.BaseRepository
import jakarta.persistence.EntityManager
import org.springframework.core.ResolvableType
import org.springframework.web.server.ResponseStatusException
import net.blueshell.api.base.BaseModelService
import org.springframework.core.GenericTypeResolver
import net.blueshell.api.base.BasePermissionEvaluator
import net.blueshell.api.base.BaseEmail
import net.blueshell.api.email.recovery.RecoveryEmail
import net.blueshell.api.model.event.EventSignUp
import net.blueshell.api.email.EventSignupEmail
import jakarta.persistence.UniqueConstraint
import net.blueshell.api.model.board.BoardMember
import net.blueshell.api.model.board.BoardDocument
import net.blueshell.api.model.board.Board
import jakarta.persistence.NamedEntityGraphs
import jakarta.persistence.NamedEntityGraph
import jakarta.persistence.NamedAttributeNode
import jakarta.persistence.NamedSubgraph
import jakarta.persistence.EntityListeners
import net.blueshell.api.model.committee.Committee
import net.blueshell.api.model.event.EventBanner
import net.blueshell.api.model.event.EventFeedback
import net.blueshell.api.model.event.EventPicture
import net.blueshell.api.model.survey.Survey
import net.blueshell.api.model.event.Guest
import jakarta.persistence.JoinTable
import net.blueshell.api.model.converter.BooleanListConverter
import net.blueshell.api.model.event.EventSignUpAnswer
import net.blueshell.api.common.hibernate.DirtyModel
import net.blueshell.api.base.DirtyAwareModel
import jakarta.persistence.Enumerated
import net.blueshell.api.common.hibernate.DirtyField
import net.blueshell.api.model.converter.StringListConverter
import jakarta.persistence.Lob
import net.blueshell.api.model.committee.CommitteeMember
import jakarta.persistence.AttributeConverter
import org.hibernate.annotations.OnDelete
import org.hibernate.annotations.OnDeleteAction
import net.blueshell.api.model.RecoveryToken
import jakarta.persistence.ElementCollection
import jakarta.persistence.CollectionTable
import net.blueshell.api.model.contribution.Contribution
import net.blueshell.api.model.Membership
import org.springframework.security.core.authority.SimpleGrantedAuthority
import net.blueshell.api.model.Telemetry
import net.blueshell.api.common.util.MappingUtil
import org.springframework.core.ResolvableTypeProvider
import org.hibernate.CallbackException
import net.blueshell.api.common.hibernate.DirtyTrackingInterceptor
import org.springframework.context.annotation.EnableAspectJAutoProxy
import org.springframework.data.domain.AuditorAware
import org.springframework.scheduling.annotation.EnableAsync
import org.springframework.core.task.TaskExecutor
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor
import org.springframework.retry.annotation.EnableRetry
import org.springframework.data.web.config.PageableHandlerMethodArgumentResolverCustomizer
import org.springframework.data.web.PageableHandlerMethodArgumentResolver
import org.springframework.security.crypto.password.PasswordEncoder
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder
import org.springframework.http.converter.json.Jackson2ObjectMapperBuilder
import org.springframework.boot.CommandLineRunner
import net.blueshell.api.service.AddressService
import net.blueshell.api.service.CommitteeService
import net.blueshell.api.service.CommitteeMemberService
import net.blueshell.api.service.event.EventSignUpService
import net.blueshell.api.service.MembershipService
import net.blueshell.api.service.contribution.ContributionService
import net.blueshell.api.service.RecoveryService
import net.blueshell.api.service.survey.SurveyService
import com.github.javafaker.Faker
import net.blueshell.api.config.DatabaseSeeder
import org.springframework.dao.DataIntegrityViolationException
import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity
import net.blueshell.api.auth.JwtAuthenticationEntryPoint
import net.blueshell.api.auth.JwtAuthFilter
import org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration
import org.springframework.security.access.hierarchicalroles.RoleHierarchy
import org.springframework.security.access.hierarchicalroles.RoleHierarchyImpl
import org.springframework.web.cors.CorsConfiguration
import org.springframework.security.config.annotation.web.builders.HttpSecurity
import org.springframework.security.web.SecurityFilterChain
import org.springframework.security.config.annotation.web.configurers.CsrfConfigurer
import org.springframework.security.config.annotation.web.configurers.SessionManagementConfigurer
import org.springframework.security.config.http.SessionCreationPolicy
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter
import org.springframework.security.config.annotation.web.configurers.AuthorizeHttpRequestsConfigurer.AuthorizationManagerRequestMatcherRegistry
import org.springframework.security.config.annotation.web.configurers.ExceptionHandlingConfigurer
import net.blueshell.api.permission.CompositePermissionEvaluator
import org.springframework.security.access.expression.method.MethodSecurityExpressionHandler
import org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler
import org.springframework.boot.web.client.RestTemplateBuilder
import org.springframework.web.client.RestTemplate
import org.springdoc.core.customizers.OpenApiCustomizer
import net.blueshell.api.dto.error.ApiErrorDTO
import org.springframework.data.web.config.EnableSpringDataWebSupport
import net.blueshell.api.config.OpenApiSchemasCustomizer
import net.blueshell.api.dto.committee.SimpleCommitteeDTO
import org.springframework.boot.autoconfigure.orm.jpa.HibernatePropertiesCustomizer
import org.springframework.beans.factory.annotation.Autowired
import net.blueshell.api.base.BaseMapper
import org.mapstruct.BeanMapping
import org.mapstruct.NullValuePropertyMappingStrategy
import org.mapstruct.MappingTarget
import org.mapstruct.AfterMapping
import net.blueshell.api.dto.user.AdvancedUserDTO
import net.blueshell.api.mapper.event.EventBannerMapper
import net.blueshell.api.mapper.survey.SurveyMapper
import net.blueshell.api.dto.event.EventDTO
import net.blueshell.api.mapper.FileMapper
import net.blueshell.api.mapper.event.GuestMapper
import net.blueshell.api.mapper.survey.AnswerMapper
import net.blueshell.api.mapper.user.SimpleUserMapper
import net.blueshell.api.dto.event.EventSignUpDTO
import net.blueshell.api.service.GuestService
import net.blueshell.api.dto.SocialDTO
import net.blueshell.api.mapper.survey.QuestionMapper
import net.blueshell.api.mapper.committee.CommitteeMemberMapper
import net.blueshell.api.dto.committee.AdvancedCommitteeDTO
import net.blueshell.api.mapper.committee.AdvancedCommitteeMapper
import net.blueshell.api.dto.contribution.ContributionDTO
import net.blueshell.api.dto.contribution.ContributionPeriodDTO
import net.blueshell.api.model.contribution.ContributionReminder
import net.blueshell.api.dto.contribution.ContributionReminderDTO
import net.blueshell.api.model.Blog
import net.blueshell.api.dto.BlogDTO
import net.blueshell.api.dto.AddressDTO
import net.blueshell.api.model.Sponsor
import net.blueshell.api.dto.SponsorDTO
import net.blueshell.api.dto.RedirectDTO
import net.blueshell.api.dto.MembershipDTO
import net.blueshell.clients.brevo.model.CreateContact
import net.blueshell.clients.brevo.model.UpdateContact
import org.springframework.context.annotation.Primary
import net.blueshell.api.mapper.BrevoContactMapper
import net.blueshell.api.service.mock.MockContactService
import org.springframework.mail.javamail.JavaMailSender
import jakarta.mail.internet.MimeMessage
import org.springframework.mail.SimpleMailMessage
import org.springframework.mail.MailException
import org.springframework.mail.MailSendException
import net.blueshell.api.service.mock.MockJavaMailSender
import org.springframework.mail.javamail.MimeMessagePreparator
import org.springframework.mail.MailPreparationException
import net.blueshell.api.service.mock.MockCalendarService
import net.blueshell.api.service.email.EmailTemplateService
import net.blueshell.api.service.email.EmailDeliveryService
import net.blueshell.api.service.contribution.ContributionReminderService
import net.blueshell.api.email.ContributionReminderEmail
import net.blueshell.api.email.recovery.MemberActivationEmail
import net.blueshell.api.email.recovery.UserActivationEmail
import net.blueshell.api.email.recovery.PasswordResetEmail
import org.springframework.mail.javamail.MimeMessageHelper
import jakarta.mail.MessagingException
import net.blueshell.api.repository.event.EventRepository
import net.blueshell.api.repository.spec.EventSpecifications
import net.blueshell.api.repository.event.EventBannerRepository
import net.blueshell.api.repository.event.EventSignUpRepository
import net.blueshell.api.controller.filter.EventSignUpFilter
import net.blueshell.api.repository.spec.EventSignUpSpecifications
import net.blueshell.api.repository.event.EventPictureRepository
import net.blueshell.api.repository.survey.AnswerRepository
import net.blueshell.api.repository.survey.SurveyRepository
import net.blueshell.api.repository.survey.QuestionRepository
import net.blueshell.api.repository.contribution.ContributionRepository
import net.blueshell.api.repository.contribution.ContributionPeriodRepository
import net.blueshell.api.repository.contribution.ContributionReminderRepository
import net.blueshell.api.common.event.job.ContributionReminderEmailEvent
import net.blueshell.api.repository.BlogRepository
import net.blueshell.api.service.event.EventBannerService
import org.springframework.web.multipart.MultipartFile
import net.blueshell.api.service.FileService
import org.springframework.http.ResponseEntity
import net.blueshell.api.repository.UserRepository
import org.springframework.security.core.userdetails.UsernameNotFoundException
import net.blueshell.api.controller.filter.UserFilter
import net.blueshell.api.repository.spec.UserSpecifications
import net.blueshell.api.repository.GuestRepository
import net.blueshell.api.repository.AddressRepository
import net.blueshell.clients.brevo.api.ContactsApi
import net.blueshell.clients.brevo.invoker.ApiClient
import net.blueshell.clients.brevo.model.GetExtendedContactDetails
import org.springframework.web.client.HttpClientErrorException
import net.blueshell.clients.brevo.model.CreateUpdateContactModel
import net.blueshell.clients.brevo.model.CreateList
import net.blueshell.clients.brevo.model.CreateModel
import net.blueshell.clients.brevo.model.AddContactToListRequest
import net.blueshell.clients.brevo.model.RemoveContactFromListRequest
import net.blueshell.api.repository.SponsorRepository
import com.google.auth.oauth2.GoogleCredentials
import com.google.auth.oauth2.ServiceAccountCredentials
import com.google.auth.http.HttpCredentialsAdapter
import com.vladsch.flexmark.util.data.MutableDataSet
import com.vladsch.flexmark.ext.gfm.strikethrough.StrikethroughExtension
import com.google.api.services.calendar.model.EventDateTime
import com.google.api.services.calendar.CalendarScopes
import net.blueshell.api.repository.RecoveryTokenRepository
import org.springframework.transaction.event.TransactionalEventListener
import org.springframework.transaction.event.TransactionPhase
import net.blueshell.api.common.event.job.RecoveryEmailEvent
import org.springframework.security.access.prepost.PreAuthorize
import net.blueshell.api.repository.committee.CommitteeRepository
import net.blueshell.api.repository.TelemetryRepository
import net.blueshell.api.repository.MemberRepository
import net.blueshell.api.controller.filter.MembershipFilter
import net.blueshell.api.repository.spec.MembershipSpecifications
import net.blueshell.api.repository.committee.CommitteeMemberRepository
import net.blueshell.api.common.event.job.SyncContactEvent
import net.blueshell.api.common.event.job.AddEventToCalendarEvent
import net.blueshell.api.common.event.job.SyncEventToCalendarEvent
import net.blueshell.api.common.event.job.RemoveEventFromCalendarEvent
import net.blueshell.api.service.survey.AnswerService
import net.blueshell.api.listener.jpa.QuestionEventListener
import net.blueshell.api.listener.jpa.MembershipEventListener
import net.blueshell.api.common.event.job.EventSignupEmailEvent
import net.blueshell.api.common.event.job.AddContactToListEvent
import net.blueshell.api.common.event.job.RemoveContactFromListEvent
import net.blueshell.api.common.event.job.CreateContributionPeriodListEvent
import net.blueshell.api.common.event.job.UpdateEventInCalendarEvent
import org.springframework.web.bind.annotation.RestController
import org.springframework.web.bind.annotation.RequestMapping
import net.blueshell.api.mapper.event.EventMapper
import net.blueshell.api.base.BaseController
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.PutMapping
import org.springframework.web.bind.annotation.PathVariable
import jakarta.ws.rs.QueryParam
import org.springframework.web.bind.annotation.GetMapping
import org.springdoc.core.annotations.ParameterObject
import org.springframework.web.bind.annotation.DeleteMapping
import net.blueshell.api.mapper.event.EventSignUpMapper
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestControllerAdvice
import org.springframework.web.bind.MethodArgumentNotValidException
import org.springframework.http.ProblemDetail
import org.springframework.validation.FieldError
import net.blueshell.api.controller.advice.ValidationProblemDetailsAdvice
import org.springframework.dao.OptimisticLockingFailureException
import net.blueshell.api.mapper.contribution.ContributionMapper
import net.blueshell.api.mapper.contribution.ContributionPeriodMapper
import net.blueshell.api.mapper.contribution.ContributionReminderMapper
import net.blueshell.api.service.BlogService
import net.blueshell.api.mapper.BlogMapper
import org.springframework.web.bind.annotation.RequestPart
import net.blueshell.api.validation.file.AllowedContentTypes
import net.blueshell.api.mapper.user.AdvancedUserMapper
import net.blueshell.api.base.AdvancedController
import net.blueshell.api.mapper.AddressMapper
import net.blueshell.api.service.SponsorService
import net.blueshell.api.mapper.SponsorMapper
import net.blueshell.api.auth.JWTAuthBase
import net.blueshell.api.dto.recovery.PasswordResetRequest
import net.blueshell.api.dto.recovery.UserActivationRequest
import net.blueshell.api.dto.response.RedirectResponseDTO
import net.blueshell.api.dto.recovery.MemberActivationRequest
import net.blueshell.api.mapper.committee.SimpleCommitteeMapper
import net.blueshell.api.service.TelemetryService
import net.blueshell.api.mapper.TelemetryMapper
import net.blueshell.api.mapper.MembershipMapper
import net.blueshell.api.dto.request.JwtRequest
import net.blueshell.api.dto.response.AuthenticationDTO
import net.blueshell.api.permission.EventPermission
import org.springframework.security.access.PermissionEvaluator
import jakarta.persistence.criteria.CriteriaQuery
import jakarta.persistence.criteria.CriteriaBuilder
import jakarta.persistence.criteria.JoinType
import jakarta.persistence.criteria.Subquery
import org.springframework.data.jpa.repository.Modifying
import net.blueshell.api.validation.date.TodayValidator
import net.blueshell.api.validation.file.FileSizeValidator
import net.blueshell.api.validation.file.AllowedContentTypesValidator
import net.blueshell.api.validation.user.UniqueUserValidator
import net.blueshell.api.validation.user.UniqueEmailValidator
import net.blueshell.api.validation.user.UniqueUsernameValidator
import net.blueshell.api.validation.user.ExistingUsernameValidator
import net.blueshell.api.validation.user.UniquePhoneNumberValidator
import net.blueshell.api.validation.user.UniqueEmail
import net.blueshell.api.validation.user.ValidMobilePhoneNumberValidator
import net.blueshell.api.validation.user.ExistingUsername
import net.blueshell.api.validation.user.UniquePhoneNumber
import net.blueshell.api.validation.event.ValidEventSignUpValidator
import net.blueshell.api.validation.event.GuestOrUserRequiredValidator
import net.blueshell.api.validation.survey.ValidAnswerValidator
import net.blueshell.api.validation.survey.ValidQuestionValidator
import net.blueshell.api.validation.survey.ValidAnswerListValidator
import net.blueshell.api.validation.survey.ValidQuestionListValidator
import net.blueshell.api.validation.survey.ValidAnswerList
import net.blueshell.api.validation.address.CountryCodeValidator
import net.blueshell.api.validation.membership.NoExistingMembershipForUserIdValidator
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.context.properties.EnableConfigurationProperties
import net.blueshell.api.config.StorageConfig
import org.springframework.data.jpa.repository.config.EnableJpaAuditing
import org.springframework.scheduling.annotation.EnableScheduling
import org.springframework.boot.SpringApplication

