FROM nginx:alpine

RUN apk add --no-cache openssl

COPY nginx-dev.conf /etc/nginx/conf.d/default.conf
COPY entrypoint-dev.sh /usr/local/bin/entrypoint-dev.sh
RUN chmod +x /usr/local/bin/entrypoint-dev.sh

EXPOSE 80 443

ENTRYPOINT ["/usr/local/bin/entrypoint-dev.sh"]
