services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "80:80"
      - "443:443"
    networks:
      - global_network
    depends_on:
      api:
        condition: service_healthy
      frontend:
        condition: service_healthy
    volumes:
      - dev-ssl:/etc/nginx/ssl
    profiles:
      - ssl

networks:
  global_network:
    driver: bridge

volumes:
  dev-ssl:
