apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
  namespace: utility-system
data:
  config.yaml: |
    storage:
      type: sqlite
      path: /data/data.db
    ui:
      title: Blueshell Esports status
      description: Uptime for the v2.esa-blueshell.nl stack.
      header: Blueshell Esports
