// This file is auto-generated by @hey-api/openapi-ts

export enum MemberType {
    ALUMNI = 'ALUMNI',
    HONORARY = 'HONORARY',
    REGULAR = 'REGULAR',
    NONE = 'NONE'
}

export type Membership = {
    id?: number;
    userId: number;
    memberType?: MemberType;
    city?: string;
    country?: string;
    startDate?: string;
    endDate?: string;
    incasso: boolean;
};

export enum Role {
    ANONYMOUS = 'ANONYMOUS',
    VEGAN = 'VEGAN',
    GUEST = 'GUEST',
    COMPANY = 'COMPANY',
    MEMBER = 'MEMBER',
    COMMITTEE = 'COMMITTEE',
    BOARD = 'BOARD',
    TREASURER = 'TREASURER',
    ADMIN = 'ADMIN',
    SYSTEM = 'SYSTEM'
}

export type AdvancedUser = {
    fullName?: string;
    discord: string;
    email: string;
    id?: number;
    initials: string;
    firstName: string;
    prefix?: string;
    lastName: string;
    username: string;
    newsletter: boolean;
    password?: string;
    roles?: Array<Role>;
    dateOfBirth: string;
    phoneNumber: string;
    nationality: string;
    photoConsent: boolean;
    ehbo: boolean;
    bhv: boolean;
    enabled?: boolean;
    createdAt?: string;
    gender?: string;
    studentNumber?: string;
    addressId?: number;
};

export type Sponsor = {
    id?: number;
    name: string;
    description: string;
};

export type Event = {
    id?: number;
    committeeId: number;
    title: string;
    description: string;
    startTime: string;
    endTime: string;
    memberPrice?: number;
    publicPrice?: number;
    approved?: boolean;
    membersOnly?: boolean;
    signUp?: boolean;
    banner?: EventBanner;
    signUpCount?: number;
    signUpForm?: Survey;
    googleId?: string;
    location?: string;
};

export type EventBanner = {
    id?: number;
    file: File;
};

export type File = {
    id?: number;
    name?: string;
    mediaType?: string;
    size?: number;
    type?: FileType;
};

export enum FileType {
    DOCUMENT = 'DOCUMENT',
    SIGNATURE = 'SIGNATURE',
    PROFILE_PICTURE = 'PROFILE_PICTURE',
    EVENT_BANNER = 'EVENT_BANNER',
    EVENT_PICTURE = 'EVENT_PICTURE',
    SPONSOR_PICTURE = 'SPONSOR_PICTURE'
}

export type Question = {
    id?: number;
    idx: number;
    surveyId?: number;
    type: QuestionType;
    label: string;
    choiceLabels?: Array<string>;
};

export enum QuestionType {
    OPEN = 'OPEN',
    RADIO = 'RADIO',
    CHECKBOX = 'CHECKBOX',
    DESCRIPTION = 'DESCRIPTION'
}

export type Survey = {
    questions: Array<Question>;
    id?: number;
    responseCount?: number;
};

export type Answer = {
    id?: number;
    questionId: number;
    optionSelections?: Array<boolean>;
    textResponse?: string;
};

export type EventSignUp = {
    id?: number;
    eventId?: number;
    answers: Array<Answer>;
    guest?: Guest;
    user?: SimpleUser;
    userId?: number;
};

export type Guest = {
    fullName: string;
    discord: string;
    email: string;
    id?: number;
    createdAt?: string;
    accessToken?: string;
};

export type SimpleUser = {
    fullName?: string;
    discord: string;
    email: string;
    id?: number;
    initials: string;
    firstName: string;
    prefix?: string;
    lastName: string;
    username: string;
    newsletter: boolean;
    password?: string;
};

export type ContributionPeriod = {
    id?: number;
    startDate: string;
    endDate: string;
    halfYearFee: number;
    fullYearFee: number;
    alumniFee: number;
    listId?: number;
};

export type AdvancedCommittee = {
    description: string;
    id?: number;
    name: string;
    members: Array<CommitteeMember>;
};

export type CommitteeMember = {
    id?: number;
    userId: number;
    committeeId?: number;
    role: string;
};

export type Address = {
    id?: number;
    userId: number;
    country: string;
    city: string;
    street: string;
    houseNumber: string;
    zipCode: string;
    createdAt?: string;
};

export enum PlatformType {
    FACEBOOK = 'FACEBOOK',
    LINKEDIN = 'LINKEDIN',
    TWITTER = 'TWITTER',
    INSTAGRAM = 'INSTAGRAM'
}

export type Telemetry = {
    id?: string;
    url?: string;
    platform?: PlatformType;
    createdAt?: string;
};

export type Contribution = {
    id?: number;
    userId: number;
    contributionPeriodId: number;
    remindedAt?: string;
};

export type ContributionReminder = {
    id?: number;
    userId: number;
    contributionPeriodId: number;
    remindedAt?: string;
};

export type Blog = {
    id?: number;
    url?: string;
    title: string;
    html: string;
    publishedAt?: string;
};

export type JwtRequest = {
    username?: string;
    password?: string;
};

export type Login = {
    token: string;
    userId: number;
    username: string;
    expiration: number;
    roles: Array<Role>;
};

export type UserActivationRequest = {
    token: string;
    username: string;
    password?: string;
};

export type PasswordResetRequest = {
    token: string;
    username: string;
    password: string;
};

export type MemberActivationRequest = {
    token: string;
    username: string;
    password?: string;
};

export type PageMetadata = {
    size?: number;
    number?: number;
    totalElements?: number;
    totalPages?: number;
};

export type PagedModelAdvancedUser = {
    content?: Array<AdvancedUser>;
    page?: PageMetadata;
};

export type Redirect = {
    id?: string;
    createdAt?: string;
    telemetry?: Telemetry;
};

export type PagedModelEvent = {
    content?: Array<Event>;
    page?: PageMetadata;
};

export type BaseDto = unknown;

/**
 * Problem Details for HTTP APIs including validation errors.
 */
export type ApiError = {
    /**
     * Problem type URI (RFC 7807).
     */
    type?: string;
    /**
     * Short, human-readable summary of the problem.
     */
    title?: string;
    /**
     * HTTP status code.
     */
    status?: number;
    /**
     * Human-readable explanation specific to this occurrence.
     */
    detail?: string;
    /**
     * A URI reference that identifies the specific occurrence.
     */
    instance?: string;
    /**
     * List of field/object validation errors (present when binding/validation fails).
     */
    errors?: Array<FieldValidationError>;
    /**
     * Trace or correlation id if available (Spring may add this via problem detail handlers).
     */
    traceId?: string;
};

/**
 * Details about a single field/object validation error.
 */
export type FieldValidationError = {
    /**
     * Object (target) name that failed validation.
     */
    objectName?: string;
    /**
     * Field that failed validation (null for global errors).
     */
    field?: string;
    /**
     * Rejected value (may be omitted for security).
     */
    rejectedValue?: {
        [key: string]: unknown;
    };
    /**
     * Human-readable validation message.
     */
    message?: string;
    /**
     * Validation code / constraint key.
     */
    code?: string;
};

export type PersonalInfo = {
    fullName: string;
    discord: string;
    email: string;
};

export type SimpleCommittee = {
    id?: number;
    name?: string;
    description?: string;
};

export type FindMembershipByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/{id}';
};

export type FindMembershipByIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindMembershipByIdError = FindMembershipByIdErrors[keyof FindMembershipByIdErrors];

export type FindMembershipByIdResponses = {
    /**
     * OK
     */
    200: Membership;
};

export type FindMembershipByIdResponse = FindMembershipByIdResponses[keyof FindMembershipByIdResponses];

export type UpdateMembershipData = {
    body: Membership;
    path: {
        id: number;
    };
    query?: never;
    url: '/{id}';
};

export type UpdateMembershipErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type UpdateMembershipError = UpdateMembershipErrors[keyof UpdateMembershipErrors];

export type UpdateMembershipResponses = {
    /**
     * OK
     */
    200: Membership;
};

export type UpdateMembershipResponse = UpdateMembershipResponses[keyof UpdateMembershipResponses];

export type ToggleUserRoleData = {
    body?: never;
    path: {
        userId: number;
    };
    query: {
        role: Role;
    };
    url: '/users/{userId}/roles';
};

export type ToggleUserRoleErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type ToggleUserRoleError = ToggleUserRoleErrors[keyof ToggleUserRoleErrors];

export type ToggleUserRoleResponses = {
    /**
     * OK
     */
    200: AdvancedUser;
};

export type ToggleUserRoleResponse = ToggleUserRoleResponses[keyof ToggleUserRoleResponses];

export type UpdateUserData = {
    body: AdvancedUser;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type UpdateUserErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: AdvancedUser;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type DeleteSponsorByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/sponsors/{id}';
};

export type DeleteSponsorByIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type DeleteSponsorByIdError = DeleteSponsorByIdErrors[keyof DeleteSponsorByIdErrors];

export type DeleteSponsorByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSponsorByIdResponse = DeleteSponsorByIdResponses[keyof DeleteSponsorByIdResponses];

export type FindSponsorByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/sponsors/{id}';
};

export type FindSponsorByIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindSponsorByIdError = FindSponsorByIdErrors[keyof FindSponsorByIdErrors];

export type FindSponsorByIdResponses = {
    /**
     * OK
     */
    200: Sponsor;
};

export type FindSponsorByIdResponse = FindSponsorByIdResponses[keyof FindSponsorByIdResponses];

export type UpdateSponsorData = {
    body: Sponsor;
    path: {
        id: number;
    };
    query?: never;
    url: '/sponsors/{id}';
};

export type UpdateSponsorErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type UpdateSponsorError = UpdateSponsorErrors[keyof UpdateSponsorErrors];

export type UpdateSponsorResponses = {
    /**
     * OK
     */
    200: Sponsor;
};

export type UpdateSponsorResponse = UpdateSponsorResponses[keyof UpdateSponsorResponses];

export type FindEventByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}';
};

export type FindEventByIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindEventByIdError = FindEventByIdErrors[keyof FindEventByIdErrors];

export type FindEventByIdResponses = {
    /**
     * OK
     */
    200: Event;
};

export type FindEventByIdResponse = FindEventByIdResponses[keyof FindEventByIdResponses];

export type UpdateEventData = {
    body: Event;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}';
};

export type UpdateEventErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type UpdateEventError = UpdateEventErrors[keyof UpdateEventErrors];

export type UpdateEventResponses = {
    /**
     * OK
     */
    200: Event;
};

export type UpdateEventResponse = UpdateEventResponses[keyof UpdateEventResponses];

export type ApproveEventData = {
    body?: never;
    path: {
        id: number;
    };
    query: {
        approved: boolean;
    };
    url: '/events/{id}/approve';
};

export type ApproveEventErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type ApproveEventError = ApproveEventErrors[keyof ApproveEventErrors];

export type ApproveEventResponses = {
    /**
     * OK
     */
    200: Event;
};

export type ApproveEventResponse = ApproveEventResponses[keyof ApproveEventResponses];

export type FindEventSignUpsByEventIdData = {
    body?: never;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/events/{eventId}/signups';
};

export type FindEventSignUpsByEventIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindEventSignUpsByEventIdError = FindEventSignUpsByEventIdErrors[keyof FindEventSignUpsByEventIdErrors];

export type FindEventSignUpsByEventIdResponses = {
    /**
     * OK
     */
    200: Array<EventSignUp>;
};

export type FindEventSignUpsByEventIdResponse = FindEventSignUpsByEventIdResponses[keyof FindEventSignUpsByEventIdResponses];

export type CreateEventSignupData = {
    body: EventSignUp;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/events/{eventId}/signups';
};

export type CreateEventSignupErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type CreateEventSignupError = CreateEventSignupErrors[keyof CreateEventSignupErrors];

export type CreateEventSignupResponses = {
    /**
     * Created
     */
    201: EventSignUp;
};

export type CreateEventSignupResponse = CreateEventSignupResponses[keyof CreateEventSignupResponses];

export type UpdateEventSignUpData = {
    body: EventSignUp;
    path: {
        eventId: number;
    };
    query?: {
        accessToken?: string;
    };
    url: '/events/{eventId}/signups';
};

export type UpdateEventSignUpErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type UpdateEventSignUpError = UpdateEventSignUpErrors[keyof UpdateEventSignUpErrors];

export type UpdateEventSignUpResponses = {
    /**
     * OK
     */
    200: EventSignUp;
};

export type UpdateEventSignUpResponse = UpdateEventSignUpResponses[keyof UpdateEventSignUpResponses];

export type DeleteContributionPeriodByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/contributionPeriods/{id}';
};

export type DeleteContributionPeriodByIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type DeleteContributionPeriodByIdError = DeleteContributionPeriodByIdErrors[keyof DeleteContributionPeriodByIdErrors];

export type DeleteContributionPeriodByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteContributionPeriodByIdResponse = DeleteContributionPeriodByIdResponses[keyof DeleteContributionPeriodByIdResponses];

export type UpdateContributionPeriodData = {
    body: ContributionPeriod;
    path: {
        id: number;
    };
    query?: never;
    url: '/contributionPeriods/{id}';
};

export type UpdateContributionPeriodErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type UpdateContributionPeriodError = UpdateContributionPeriodErrors[keyof UpdateContributionPeriodErrors];

export type UpdateContributionPeriodResponses = {
    /**
     * OK
     */
    200: ContributionPeriod;
};

export type UpdateContributionPeriodResponse = UpdateContributionPeriodResponses[keyof UpdateContributionPeriodResponses];

export type DeleteCommitteeByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/committees/{id}';
};

export type DeleteCommitteeByIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type DeleteCommitteeByIdError = DeleteCommitteeByIdErrors[keyof DeleteCommitteeByIdErrors];

export type DeleteCommitteeByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteCommitteeByIdResponse = DeleteCommitteeByIdResponses[keyof DeleteCommitteeByIdResponses];

export type UpdateCommitteeData = {
    body: AdvancedCommittee;
    path: {
        id: number;
    };
    query?: never;
    url: '/committees/{id}';
};

export type UpdateCommitteeErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type UpdateCommitteeError = UpdateCommitteeErrors[keyof UpdateCommitteeErrors];

export type UpdateCommitteeResponses = {
    /**
     * OK
     */
    200: AdvancedCommittee;
};

export type UpdateCommitteeResponse = UpdateCommitteeResponses[keyof UpdateCommitteeResponses];

export type DeleteAddressByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/addresses/{id}';
};

export type DeleteAddressByIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type DeleteAddressByIdError = DeleteAddressByIdErrors[keyof DeleteAddressByIdErrors];

export type DeleteAddressByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteAddressByIdResponse = DeleteAddressByIdResponses[keyof DeleteAddressByIdResponses];

export type FindAddressByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/addresses/{id}';
};

export type FindAddressByIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindAddressByIdError = FindAddressByIdErrors[keyof FindAddressByIdErrors];

export type FindAddressByIdResponses = {
    /**
     * OK
     */
    200: Address;
};

export type FindAddressByIdResponse = FindAddressByIdResponses[keyof FindAddressByIdResponses];

export type UpdateAddressData = {
    body: Address;
    path: {
        id: number;
    };
    query?: never;
    url: '/addresses/{id}';
};

export type UpdateAddressErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type UpdateAddressError = UpdateAddressErrors[keyof UpdateAddressErrors];

export type UpdateAddressResponses = {
    /**
     * OK
     */
    200: Address;
};

export type UpdateAddressResponse = UpdateAddressResponses[keyof UpdateAddressResponses];

export type FindUsersData = {
    body?: never;
    path?: never;
    query?: {
        isMember?: boolean;
        /**
         * Zero-based page index (0..N)
         */
        page?: number;
        /**
         * The size of the page to be returned
         */
        size?: number;
        /**
         * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         */
        sort?: Array<string>;
    };
    url: '/users';
};

export type FindUsersErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindUsersError = FindUsersErrors[keyof FindUsersErrors];

export type FindUsersResponses = {
    /**
     * OK
     */
    200: PagedModelAdvancedUser;
};

export type FindUsersResponse = FindUsersResponses[keyof FindUsersResponses];

export type CreateUserData = {
    body: AdvancedUser;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateUserErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Created
     */
    201: AdvancedUser;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type UploadSignatureData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/users/signature';
};

export type UploadSignatureErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type UploadSignatureError = UploadSignatureErrors[keyof UploadSignatureErrors];

export type UploadSignatureResponses = {
    /**
     * Created
     */
    201: File;
};

export type UploadSignatureResponse = UploadSignatureResponses[keyof UploadSignatureResponses];

export type CreateMemberData = {
    body: AdvancedUser;
    path?: never;
    query?: never;
    url: '/users/member';
};

export type CreateMemberErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type CreateMemberError = CreateMemberErrors[keyof CreateMemberErrors];

export type CreateMemberResponses = {
    /**
     * Created
     */
    201: AdvancedUser;
};

export type CreateMemberResponse = CreateMemberResponses[keyof CreateMemberResponses];

export type CreateGuestUserData = {
    body: SimpleUser;
    path?: never;
    query?: never;
    url: '/users/guest';
};

export type CreateGuestUserErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type CreateGuestUserError = CreateGuestUserErrors[keyof CreateGuestUserErrors];

export type CreateGuestUserResponses = {
    /**
     * Created
     */
    201: SimpleUser;
};

export type CreateGuestUserResponse = CreateGuestUserResponses[keyof CreateGuestUserResponses];

export type CreateTelemetryData = {
    body?: never;
    path?: never;
    query: {
        platform: PlatformType;
        url: string;
    };
    url: '/telemetry';
};

export type CreateTelemetryErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type CreateTelemetryError = CreateTelemetryErrors[keyof CreateTelemetryErrors];

export type CreateTelemetryResponses = {
    /**
     * Created
     */
    201: Telemetry;
};

export type CreateTelemetryResponse = CreateTelemetryResponses[keyof CreateTelemetryResponses];

export type DeleteRedirectData = {
    body?: never;
    path?: never;
    query: {
        id: number;
    };
    url: '/telemetry/redirect';
};

export type DeleteRedirectErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type DeleteRedirectError = DeleteRedirectErrors[keyof DeleteRedirectErrors];

export type DeleteRedirectResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRedirectResponse = DeleteRedirectResponses[keyof DeleteRedirectResponses];

export type CreateRedirectData = {
    body?: never;
    path?: never;
    query: {
        id: number;
    };
    url: '/telemetry/redirect';
};

export type CreateRedirectErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type CreateRedirectError = CreateRedirectErrors[keyof CreateRedirectErrors];

export type CreateRedirectResponses = {
    /**
     * Created
     */
    201: string;
};

export type CreateRedirectResponse = CreateRedirectResponses[keyof CreateRedirectResponses];

export type FindSponsorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sponsors';
};

export type FindSponsorsErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindSponsorsError = FindSponsorsErrors[keyof FindSponsorsErrors];

export type FindSponsorsResponses = {
    /**
     * OK
     */
    200: Array<Sponsor>;
};

export type FindSponsorsResponse = FindSponsorsResponses[keyof FindSponsorsResponses];

export type CreateSponsorData = {
    body: Sponsor;
    path?: never;
    query?: never;
    url: '/sponsors';
};

export type CreateSponsorErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type CreateSponsorError = CreateSponsorErrors[keyof CreateSponsorErrors];

export type CreateSponsorResponses = {
    /**
     * Created
     */
    201: Sponsor;
};

export type CreateSponsorResponse = CreateSponsorResponses[keyof CreateSponsorResponses];

export type FindMembershipsData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
    };
    url: '/memberships';
};

export type FindMembershipsErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindMembershipsError = FindMembershipsErrors[keyof FindMembershipsErrors];

export type FindMembershipsResponses = {
    /**
     * OK
     */
    200: Array<Membership>;
};

export type FindMembershipsResponse = FindMembershipsResponses[keyof FindMembershipsResponses];

export type CreateMembershipData = {
    body: Membership;
    path?: never;
    query?: never;
    url: '/memberships';
};

export type CreateMembershipErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type CreateMembershipError = CreateMembershipErrors[keyof CreateMembershipErrors];

export type CreateMembershipResponses = {
    /**
     * Created
     */
    201: Membership;
};

export type CreateMembershipResponse = CreateMembershipResponses[keyof CreateMembershipResponses];

export type BoardCreateMembershipData = {
    body: Membership;
    path?: never;
    query?: never;
    url: '/memberships/member';
};

export type BoardCreateMembershipErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type BoardCreateMembershipError = BoardCreateMembershipErrors[keyof BoardCreateMembershipErrors];

export type BoardCreateMembershipResponses = {
    /**
     * Created
     */
    201: Membership;
};

export type BoardCreateMembershipResponse = BoardCreateMembershipResponses[keyof BoardCreateMembershipResponses];

export type FindEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Zero-based page index (0..N)
         */
        page?: number;
        /**
         * The size of the page to be returned
         */
        size?: number;
        /**
         * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         */
        sort?: Array<string>;
        from?: string;
        to?: string;
        approved?: boolean;
        committeeId?: number;
        titleContains?: string;
    };
    url: '/events';
};

export type FindEventsErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindEventsError = FindEventsErrors[keyof FindEventsErrors];

export type FindEventsResponses = {
    /**
     * OK
     */
    200: PagedModelEvent;
};

export type FindEventsResponse = FindEventsResponses[keyof FindEventsResponses];

export type CreateEventData = {
    body: Event;
    path?: never;
    query?: never;
    url: '/events';
};

export type CreateEventErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type CreateEventError = CreateEventErrors[keyof CreateEventErrors];

export type CreateEventResponses = {
    /**
     * Created
     */
    201: Event;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type UploadEventBannerData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/events/banners';
};

export type UploadEventBannerErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type UploadEventBannerError = UploadEventBannerErrors[keyof UploadEventBannerErrors];

export type UploadEventBannerResponses = {
    /**
     * Created
     */
    201: File;
};

export type UploadEventBannerResponse = UploadEventBannerResponses[keyof UploadEventBannerResponses];

export type FindContributionsData = {
    body?: never;
    path?: never;
    query?: {
        contributionPeriodId?: number;
    };
    url: '/contributions';
};

export type FindContributionsErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindContributionsError = FindContributionsErrors[keyof FindContributionsErrors];

export type FindContributionsResponses = {
    /**
     * OK
     */
    200: Array<Contribution>;
};

export type FindContributionsResponse = FindContributionsResponses[keyof FindContributionsResponses];

export type CreateContributionData = {
    body: Contribution;
    path?: never;
    query?: never;
    url: '/contributions';
};

export type CreateContributionErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type CreateContributionError = CreateContributionErrors[keyof CreateContributionErrors];

export type CreateContributionResponses = {
    /**
     * Created
     */
    201: Contribution;
};

export type CreateContributionResponse = CreateContributionResponses[keyof CreateContributionResponses];

export type FindContributionRemindersData = {
    body?: never;
    path?: never;
    query?: {
        contributionPeriodId?: number;
    };
    url: '/contributionReminders';
};

export type FindContributionRemindersErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindContributionRemindersError = FindContributionRemindersErrors[keyof FindContributionRemindersErrors];

export type FindContributionRemindersResponses = {
    /**
     * OK
     */
    200: Array<ContributionReminder>;
};

export type FindContributionRemindersResponse = FindContributionRemindersResponses[keyof FindContributionRemindersResponses];

export type SendContributionReminderData = {
    body: ContributionReminder;
    path?: never;
    query?: never;
    url: '/contributionReminders';
};

export type SendContributionReminderErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type SendContributionReminderError = SendContributionReminderErrors[keyof SendContributionReminderErrors];

export type SendContributionReminderResponses = {
    /**
     * Created
     */
    201: ContributionReminder;
};

export type SendContributionReminderResponse = SendContributionReminderResponses[keyof SendContributionReminderResponses];

export type SendContributionReminderBatchData = {
    body: Array<ContributionReminder>;
    path?: never;
    query?: never;
    url: '/contributionReminders/batch';
};

export type SendContributionReminderBatchErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type SendContributionReminderBatchError = SendContributionReminderBatchErrors[keyof SendContributionReminderBatchErrors];

export type SendContributionReminderBatchResponses = {
    /**
     * Created
     */
    201: Array<ContributionReminder>;
};

export type SendContributionReminderBatchResponse = SendContributionReminderBatchResponses[keyof SendContributionReminderBatchResponses];

export type FindContributionPeriodsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/contributionPeriods';
};

export type FindContributionPeriodsErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindContributionPeriodsError = FindContributionPeriodsErrors[keyof FindContributionPeriodsErrors];

export type FindContributionPeriodsResponses = {
    /**
     * OK
     */
    200: Array<ContributionPeriod>;
};

export type FindContributionPeriodsResponse = FindContributionPeriodsResponses[keyof FindContributionPeriodsResponses];

export type CreateContributionPeriodData = {
    body: ContributionPeriod;
    path?: never;
    query?: never;
    url: '/contributionPeriods';
};

export type CreateContributionPeriodErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type CreateContributionPeriodError = CreateContributionPeriodErrors[keyof CreateContributionPeriodErrors];

export type CreateContributionPeriodResponses = {
    /**
     * Created
     */
    201: ContributionPeriod;
};

export type CreateContributionPeriodResponse = CreateContributionPeriodResponses[keyof CreateContributionPeriodResponses];

export type FindCommitteesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/committees';
};

export type FindCommitteesErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindCommitteesError = FindCommitteesErrors[keyof FindCommitteesErrors];

export type FindCommitteesResponses = {
    /**
     * OK
     */
    200: Array<BaseDto>;
};

export type FindCommitteesResponse = FindCommitteesResponses[keyof FindCommitteesResponses];

export type CreateCommitteeData = {
    body: AdvancedCommittee;
    path?: never;
    query?: never;
    url: '/committees';
};

export type CreateCommitteeErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type CreateCommitteeError = CreateCommitteeErrors[keyof CreateCommitteeErrors];

export type CreateCommitteeResponses = {
    /**
     * Created
     */
    201: AdvancedCommittee;
};

export type CreateCommitteeResponse = CreateCommitteeResponses[keyof CreateCommitteeResponses];

export type FindBlogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/blogs';
};

export type FindBlogsErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindBlogsError = FindBlogsErrors[keyof FindBlogsErrors];

export type FindBlogsResponses = {
    /**
     * OK
     */
    200: Array<Blog>;
};

export type FindBlogsResponse = FindBlogsResponses[keyof FindBlogsResponses];

export type CreateBlogData = {
    body: Blog;
    path?: never;
    query?: never;
    url: '/blogs';
};

export type CreateBlogErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type CreateBlogError = CreateBlogErrors[keyof CreateBlogErrors];

export type CreateBlogResponses = {
    /**
     * Created
     */
    201: Blog;
};

export type CreateBlogResponse = CreateBlogResponses[keyof CreateBlogResponses];

export type DeleteByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/blogs/{id}';
};

export type DeleteByIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type DeleteByIdError = DeleteByIdErrors[keyof DeleteByIdErrors];

export type DeleteByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteByIdResponse = DeleteByIdResponses[keyof DeleteByIdResponses];

export type FindBlogByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/blogs/{id}';
};

export type FindBlogByIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindBlogByIdError = FindBlogByIdErrors[keyof FindBlogByIdErrors];

export type FindBlogByIdResponses = {
    /**
     * OK
     */
    200: Blog;
};

export type FindBlogByIdResponse = FindBlogByIdResponses[keyof FindBlogByIdResponses];

export type UpdateBlogData = {
    body: Blog;
    path: {
        id: number;
    };
    query?: never;
    url: '/blogs/{id}';
};

export type UpdateBlogErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type UpdateBlogError = UpdateBlogErrors[keyof UpdateBlogErrors];

export type UpdateBlogResponses = {
    /**
     * OK
     */
    200: Blog;
};

export type UpdateBlogResponse = UpdateBlogResponses[keyof UpdateBlogResponses];

export type AuthenticateData = {
    body: JwtRequest;
    path?: never;
    query?: never;
    url: '/auth';
};

export type AuthenticateErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type AuthenticateError = AuthenticateErrors[keyof AuthenticateErrors];

export type AuthenticateResponses = {
    /**
     * OK
     */
    200: Login;
};

export type AuthenticateResponse = AuthenticateResponses[keyof AuthenticateResponses];

export type UserActivateData = {
    body: UserActivationRequest;
    path?: never;
    query?: never;
    url: '/auth/user/activate';
};

export type UserActivateErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type UserActivateError = UserActivateErrors[keyof UserActivateErrors];

export type UserActivateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ResetPasswordData = {
    body?: never;
    path?: never;
    query: {
        username: string;
    };
    url: '/auth/password';
};

export type ResetPasswordErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type SetPasswordData = {
    body: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/auth/password';
};

export type SetPasswordErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type SetPasswordError = SetPasswordErrors[keyof SetPasswordErrors];

export type SetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MemberActivateData = {
    body: MemberActivationRequest;
    path?: never;
    query?: never;
    url: '/auth/member/activate';
};

export type MemberActivateErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type MemberActivateError = MemberActivateErrors[keyof MemberActivateErrors];

export type MemberActivateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type FindAllAddressesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/addresses';
};

export type FindAllAddressesErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindAllAddressesError = FindAllAddressesErrors[keyof FindAllAddressesErrors];

export type FindAllAddressesResponses = {
    /**
     * OK
     */
    200: Array<Address>;
};

export type FindAllAddressesResponse = FindAllAddressesResponses[keyof FindAllAddressesResponses];

export type CreateAddressData = {
    body: Address;
    path?: never;
    query?: never;
    url: '/addresses';
};

export type CreateAddressErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type CreateAddressError = CreateAddressErrors[keyof CreateAddressErrors];

export type CreateAddressResponses = {
    /**
     * Created
     */
    201: Address;
};

export type CreateAddressResponse = CreateAddressResponses[keyof CreateAddressResponses];

export type DeleteUserByIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/users/{userId}';
};

export type DeleteUserByIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type DeleteUserByIdError = DeleteUserByIdErrors[keyof DeleteUserByIdErrors];

export type DeleteUserByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteUserByIdResponse = DeleteUserByIdResponses[keyof DeleteUserByIdResponses];

export type FindUserByIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/users/{userId}';
};

export type FindUserByIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindUserByIdError = FindUserByIdErrors[keyof FindUserByIdErrors];

export type FindUserByIdResponses = {
    /**
     * OK
     */
    200: AdvancedUser;
};

export type FindUserByIdResponse = FindUserByIdResponses[keyof FindUserByIdResponses];

export type FindTelemetryByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/telemetry/{id}';
};

export type FindTelemetryByIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindTelemetryByIdError = FindTelemetryByIdErrors[keyof FindTelemetryByIdErrors];

export type FindTelemetryByIdResponses = {
    /**
     * OK
     */
    200: Telemetry;
};

export type FindTelemetryByIdResponse = FindTelemetryByIdResponses[keyof FindTelemetryByIdResponses];

export type FindRedirectsData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
    };
    url: '/telemetry/redirects';
};

export type FindRedirectsErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindRedirectsError = FindRedirectsErrors[keyof FindRedirectsErrors];

export type FindRedirectsResponses = {
    /**
     * OK
     */
    200: Array<Redirect>;
};

export type FindRedirectsResponse = FindRedirectsResponses[keyof FindRedirectsResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type HealthCheckError = HealthCheckErrors[keyof HealthCheckErrors];

export type HealthCheckResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type FindEventSignUpsData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
        userId?: number;
        committeeId?: number;
        approved?: boolean;
        eventId?: number;
    };
    url: '/events/signups';
};

export type FindEventSignUpsErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindEventSignUpsError = FindEventSignUpsErrors[keyof FindEventSignUpsErrors];

export type FindEventSignUpsResponses = {
    /**
     * OK
     */
    200: Array<EventSignUp>;
};

export type FindEventSignUpsResponse = FindEventSignUpsResponses[keyof FindEventSignUpsResponses];

export type FindEventSignUpByAccessTokenData = {
    body?: never;
    path: {
        accessToken: string;
    };
    query?: never;
    url: '/events/signups/byAccessToken/{accessToken}';
};

export type FindEventSignUpByAccessTokenErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindEventSignUpByAccessTokenError = FindEventSignUpByAccessTokenErrors[keyof FindEventSignUpByAccessTokenErrors];

export type FindEventSignUpByAccessTokenResponses = {
    /**
     * OK
     */
    200: EventSignUp;
};

export type FindEventSignUpByAccessTokenResponse = FindEventSignUpByAccessTokenResponses[keyof FindEventSignUpByAccessTokenResponses];

export type DownloadEventBannerData = {
    body?: never;
    path: {
        bannerId: number;
    };
    query?: never;
    url: '/events/banners/{bannerId}';
};

export type DownloadEventBannerErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type DownloadEventBannerError = DownloadEventBannerErrors[keyof DownloadEventBannerErrors];

export type DownloadEventBannerResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadEventBannerResponse = DownloadEventBannerResponses[keyof DownloadEventBannerResponses];

export type FindContributionsByPeriodIdData = {
    body?: never;
    path: {
        periodId: number;
    };
    query?: never;
    url: '/contributionPeriods/{periodId}/contributions';
};

export type FindContributionsByPeriodIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindContributionsByPeriodIdError = FindContributionsByPeriodIdErrors[keyof FindContributionsByPeriodIdErrors];

export type FindContributionsByPeriodIdResponses = {
    /**
     * OK
     */
    200: Array<Contribution>;
};

export type FindContributionsByPeriodIdResponse = FindContributionsByPeriodIdResponses[keyof FindContributionsByPeriodIdResponses];

export type FindCurrentContributionPeriodData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/contributionPeriods/current';
};

export type FindCurrentContributionPeriodErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindCurrentContributionPeriodError = FindCurrentContributionPeriodErrors[keyof FindCurrentContributionPeriodErrors];

export type FindCurrentContributionPeriodResponses = {
    /**
     * OK
     */
    200: ContributionPeriod;
};

export type FindCurrentContributionPeriodResponse = FindCurrentContributionPeriodResponses[keyof FindCurrentContributionPeriodResponses];

export type FindCommitteeByIdData = {
    body?: never;
    path: {
        committeeId: number;
    };
    query?: never;
    url: '/committees/{committeeId}';
};

export type FindCommitteeByIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindCommitteeByIdError = FindCommitteeByIdErrors[keyof FindCommitteeByIdErrors];

export type FindCommitteeByIdResponses = {
    /**
     * OK
     */
    200: BaseDto;
};

export type FindCommitteeByIdResponse = FindCommitteeByIdResponses[keyof FindCommitteeByIdResponses];

export type FindCommitteesForCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/committeeMembers/committees';
};

export type FindCommitteesForCurrentUserErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type FindCommitteesForCurrentUserError = FindCommitteesForCurrentUserErrors[keyof FindCommitteesForCurrentUserErrors];

export type FindCommitteesForCurrentUserResponses = {
    /**
     * OK
     */
    200: Array<BaseDto>;
};

export type FindCommitteesForCurrentUserResponse = FindCommitteesForCurrentUserResponses[keyof FindCommitteesForCurrentUserResponses];

export type DeleteEventByIdData = {
    body?: never;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/events/{eventId}';
};

export type DeleteEventByIdErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type DeleteEventByIdError = DeleteEventByIdErrors[keyof DeleteEventByIdErrors];

export type DeleteEventByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteEventByIdResponse = DeleteEventByIdResponses[keyof DeleteEventByIdResponses];

export type DeleteEventSignupData = {
    body?: never;
    path: {
        eventSignupId: number;
    };
    query?: {
        accessToken?: string;
    };
    url: '/events/signups/{eventSignupId}';
};

export type DeleteEventSignupErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type DeleteEventSignupError = DeleteEventSignupErrors[keyof DeleteEventSignupErrors];

export type DeleteEventSignupResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteEventSignupResponse = DeleteEventSignupResponses[keyof DeleteEventSignupResponses];

export type DeleteContributionData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/contributions/{id}';
};

export type DeleteContributionErrors = {
    /**
     * Validation error
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden (access denied)
     */
    403: ApiError;
    /**
     * Not Found
     */
    404: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type DeleteContributionError = DeleteContributionErrors[keyof DeleteContributionErrors];

export type DeleteContributionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteContributionResponse = DeleteContributionResponses[keyof DeleteContributionResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8080' | (string & {});
};
