// This file is auto-generated by @hey-api/openapi-ts

export enum MemberType {
    ALUMNI = 'ALUMNI',
    HONORARY = 'HONORARY',
    REGULAR = 'REGULAR',
    NONE = 'NONE'
}

export type Membership = {
    id?: number;
    userId: number;
    memberType: MemberType;
    city: string;
    country: string;
    startDate?: string;
    endDate?: string;
    incasso: boolean;
};

export enum Role {
    ANONYMOUS = 'ANONYMOUS',
    GUEST = 'GUEST',
    COMPANY = 'COMPANY',
    MEMBER = 'MEMBER',
    VEGAN = 'VEGAN',
    COMMITTEE = 'COMMITTEE',
    BOARD = 'BOARD',
    TREASURER = 'TREASURER',
    ADMIN = 'ADMIN',
    SYSTEM = 'SYSTEM'
}

export type AdvancedUser = {
    id?: number;
    initials: string;
    firstName: string;
    prefix?: string;
    lastName: string;
    fullName?: string;
    username: string;
    discord: string;
    email: string;
    newsletter: boolean;
    roles?: Array<Role>;
    dateOfBirth: string;
    phoneNumber: string;
    nationality: string;
    photoConsent: boolean;
    ehbo: boolean;
    bhv: boolean;
    enabled?: boolean;
    createdAt?: string;
    gender?: string;
    studentNumber?: string;
};

export type Sponsor = {
    id?: number;
    name: string;
    description: string;
};

export type Event = {
    id?: number;
    committeeId: number;
    committee?: SimpleCommittee;
    title: string;
    startTime: string;
    endTime: string;
    memberPrice?: number;
    publicPrice?: number;
    visible?: boolean;
    membersOnly?: boolean;
    signUp?: boolean;
    banner?: File;
    signUpForm?: Array<FormQuestion>;
    description: string;
    location?: string;
};

export type File = {
    id?: number;
    name?: string;
    url?: string;
    uploaderId?: number;
    createdAt?: string;
    mediaType?: string;
    size?: number;
    fileName?: string;
    fileType?: FileType;
    base64Content?: string;
};

export enum FileType {
    DOCUMENT = 'DOCUMENT',
    SIGNATURE = 'SIGNATURE',
    PROFILE_PICTURE = 'PROFILE_PICTURE',
    EVENT_BANNER = 'EVENT_BANNER',
    EVENT_PICTURE = 'EVENT_PICTURE',
    SPONSOR_PICTURE = 'SPONSOR_PICTURE'
}

export type FormQuestion = {
    prompt: string;
    type: string;
    options?: Array<string>;
};

export type SimpleCommittee = {
    id?: number;
    name?: string;
    description?: string;
};

export type EventSignUp = {
    id?: number;
    eventId?: number;
    formAnswers?: Array<{
        [key: string]: unknown;
    }>;
    guest?: Guest;
    user?: SimpleUser;
};

export type Guest = {
    id?: number;
    fullName: string;
    discord: string;
    email: string;
    createdAt?: string;
    accessToken?: string;
};

export type SimpleUser = {
    id?: number;
    initials: string;
    firstName: string;
    prefix?: string;
    lastName: string;
    fullName?: string;
    username: string;
    discord: string;
    email: string;
    newsletter: boolean;
};

export type Contribution = {
    id?: number;
    userId: number;
    contributionPeriodId: number;
    paid: boolean;
    remindedAt?: string;
};

export type ContributionPeriod = {
    id?: number;
    startDate: string;
    endDate: string;
    halfYearFee: number;
    fullYearFee: number;
    alumniFee: number;
    listId?: number;
};

export type AdvancedCommittee = {
    id?: number;
    name: string;
    description?: string;
    members?: Array<CommitteeMember>;
};

export type CommitteeMember = {
    id?: number;
    userId: number;
    committeeId: number;
    role: string;
};

export type BaseDto = {
    [key: string]: unknown;
};

export type Address = {
    id?: number;
    userId: number;
    country: string;
    city: string;
    street: string;
    houseNumber: string;
    zipCode: string;
    createdAt?: string;
};

export enum PlatformType {
    FACEBOOK = 'FACEBOOK',
    LINKEDIN = 'LINKEDIN',
    TWITTER = 'TWITTER',
    INSTAGRAM = 'INSTAGRAM'
}

export type Telemetry = {
    id?: string;
    url?: string;
    platform?: PlatformType;
    createdAt?: string;
};

export type Blog = {
    id?: number;
    url?: string;
    title: string;
    html: string;
    publishedAt?: string;
};

export type JwtRequest = {
    username?: string;
    password?: string;
};

export type Login = {
    token: string;
    userId: number;
    username: string;
    expiration: number;
    roles: Array<Role>;
};

export type UserActivationRequest = {
    token: string;
    username: string;
    password?: string;
};

export type PasswordResetRequest = {
    token: string;
    username: string;
    password?: string;
};

export type MemberActivationRequest = {
    token: string;
    username: string;
    password?: string;
};

export type PageAdvancedUser = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<AdvancedUser>;
    number?: number;
    sort?: SortObject;
    pageable?: PageableObject;
    numberOfElements?: number;
    first?: boolean;
    last?: boolean;
    empty?: boolean;
};

export type PageableObject = {
    offset?: number;
    sort?: SortObject;
    unpaged?: boolean;
    pageNumber?: number;
    paged?: boolean;
    pageSize?: number;
};

export type SortObject = {
    empty?: boolean;
    unsorted?: boolean;
    sorted?: boolean;
};

export type Redirect = {
    id?: string;
    createdAt?: string;
    telemetry?: Telemetry;
};

export type PageEvent = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<Event>;
    number?: number;
    sort?: SortObject;
    pageable?: PageableObject;
    numberOfElements?: number;
    first?: boolean;
    last?: boolean;
    empty?: boolean;
};

export type FindMembershipByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/{id}';
};

export type FindMembershipByIdResponses = {
    /**
     * OK
     */
    200: Membership;
};

export type FindMembershipByIdResponse = FindMembershipByIdResponses[keyof FindMembershipByIdResponses];

export type UpdateMembershipData = {
    body: Membership;
    path: {
        id: number;
    };
    query?: never;
    url: '/{id}';
};

export type UpdateMembershipResponses = {
    /**
     * OK
     */
    200: Membership;
};

export type UpdateMembershipResponse = UpdateMembershipResponses[keyof UpdateMembershipResponses];

export type ToggleUserRoleData = {
    body?: never;
    path: {
        userId: number;
    };
    query: {
        role: Role;
    };
    url: '/users/{userId}/roles';
};

export type ToggleUserRoleResponses = {
    /**
     * OK
     */
    200: AdvancedUser;
};

export type ToggleUserRoleResponse = ToggleUserRoleResponses[keyof ToggleUserRoleResponses];

export type UpdateUserData = {
    body: AdvancedUser;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: AdvancedUser;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type DeleteSponsorByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/sponsors/{id}';
};

export type DeleteSponsorByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSponsorByIdResponse = DeleteSponsorByIdResponses[keyof DeleteSponsorByIdResponses];

export type FindSponsorByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/sponsors/{id}';
};

export type FindSponsorByIdResponses = {
    /**
     * OK
     */
    200: Sponsor;
};

export type FindSponsorByIdResponse = FindSponsorByIdResponses[keyof FindSponsorByIdResponses];

export type UpdateSponsorData = {
    body: Sponsor;
    path: {
        id: number;
    };
    query?: never;
    url: '/sponsors/{id}';
};

export type UpdateSponsorResponses = {
    /**
     * OK
     */
    200: Sponsor;
};

export type UpdateSponsorResponse = UpdateSponsorResponses[keyof UpdateSponsorResponses];

export type FindEventByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}';
};

export type FindEventByIdResponses = {
    /**
     * OK
     */
    200: Event;
};

export type FindEventByIdResponse = FindEventByIdResponses[keyof FindEventByIdResponses];

export type UpdateEventData = {
    body: Event;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}';
};

export type UpdateEventResponses = {
    /**
     * OK
     */
    200: Event;
};

export type UpdateEventResponse = UpdateEventResponses[keyof UpdateEventResponses];

export type FindEventSignUpsByEventIdData = {
    body?: never;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/events/{eventId}/signups';
};

export type FindEventSignUpsByEventIdResponses = {
    /**
     * OK
     */
    200: Array<EventSignUp>;
};

export type FindEventSignUpsByEventIdResponse = FindEventSignUpsByEventIdResponses[keyof FindEventSignUpsByEventIdResponses];

export type UpdateEventSignUpData = {
    body: EventSignUp;
    path: {
        eventId: number;
    };
    query?: {
        accessToken?: string;
    };
    url: '/events/{eventId}/signups';
};

export type UpdateEventSignUpResponses = {
    /**
     * OK
     */
    200: EventSignUp;
};

export type UpdateEventSignUpResponse = UpdateEventSignUpResponses[keyof UpdateEventSignUpResponses];

export type SetContributionPaidData = {
    body?: never;
    path: {
        id: number;
    };
    query: {
        paid: boolean;
    };
    url: '/contributions/{id}/paid';
};

export type SetContributionPaidResponses = {
    /**
     * OK
     */
    200: Contribution;
};

export type SetContributionPaidResponse = SetContributionPaidResponses[keyof SetContributionPaidResponses];

export type SendContributionReminderData = {
    body?: never;
    path: {
        periodId: number;
    };
    query?: never;
    url: '/contributionPeriods/{periodId}/contributions/remind';
};

export type SendContributionReminderResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteContributionPeriodByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/contributionPeriods/{id}';
};

export type DeleteContributionPeriodByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteContributionPeriodByIdResponse = DeleteContributionPeriodByIdResponses[keyof DeleteContributionPeriodByIdResponses];

export type UpdateContributionPeriodData = {
    body: ContributionPeriod;
    path: {
        id: number;
    };
    query?: never;
    url: '/contributionPeriods/{id}';
};

export type UpdateContributionPeriodResponses = {
    /**
     * OK
     */
    200: ContributionPeriod;
};

export type UpdateContributionPeriodResponse = UpdateContributionPeriodResponses[keyof UpdateContributionPeriodResponses];

export type DeleteCommitteeByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/committees/{id}';
};

export type DeleteCommitteeByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteCommitteeByIdResponse = DeleteCommitteeByIdResponses[keyof DeleteCommitteeByIdResponses];

export type UpdateCommitteeData = {
    body: AdvancedCommittee;
    path: {
        id: number;
    };
    query?: never;
    url: '/committees/{id}';
};

export type UpdateCommitteeResponses = {
    /**
     * OK
     */
    200: BaseDto;
};

export type UpdateCommitteeResponse = UpdateCommitteeResponses[keyof UpdateCommitteeResponses];

export type DeleteAddressByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/addresses/{id}';
};

export type DeleteAddressByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteAddressByIdResponse = DeleteAddressByIdResponses[keyof DeleteAddressByIdResponses];

export type FindAddressByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/addresses/{id}';
};

export type FindAddressByIdResponses = {
    /**
     * OK
     */
    200: Address;
};

export type FindAddressByIdResponse = FindAddressByIdResponses[keyof FindAddressByIdResponses];

export type UpdateAddressData = {
    body: Address;
    path: {
        id: number;
    };
    query?: never;
    url: '/addresses/{id}';
};

export type UpdateAddressResponses = {
    /**
     * OK
     */
    200: Address;
};

export type UpdateAddressResponse = UpdateAddressResponses[keyof UpdateAddressResponses];

export type FindUsersData = {
    body?: never;
    path?: never;
    query?: {
        isMember?: boolean;
        /**
         * Zero-based page index (0..N)
         */
        page?: number;
        /**
         * The size of the page to be returned
         */
        size?: number;
        /**
         * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         */
        sort?: Array<string>;
    };
    url: '/users';
};

export type FindUsersResponses = {
    /**
     * OK
     */
    200: PageAdvancedUser;
};

export type FindUsersResponse = FindUsersResponses[keyof FindUsersResponses];

export type CreateUserData = {
    body: AdvancedUser;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateUserResponses = {
    /**
     * OK
     */
    200: AdvancedUser;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type CreateMemberData = {
    body: AdvancedUser;
    path?: never;
    query?: never;
    url: '/users/member';
};

export type CreateMemberResponses = {
    /**
     * OK
     */
    200: AdvancedUser;
};

export type CreateMemberResponse = CreateMemberResponses[keyof CreateMemberResponses];

export type CreateGuestUserData = {
    body: SimpleUser;
    path?: never;
    query?: never;
    url: '/users/guest';
};

export type CreateGuestUserResponses = {
    /**
     * OK
     */
    200: SimpleUser;
};

export type CreateGuestUserResponse = CreateGuestUserResponses[keyof CreateGuestUserResponses];

export type CreateTelemetryData = {
    body?: never;
    path?: never;
    query: {
        platform: PlatformType;
        url: string;
    };
    url: '/telemetry';
};

export type CreateTelemetryResponses = {
    /**
     * OK
     */
    200: Telemetry;
};

export type CreateTelemetryResponse = CreateTelemetryResponses[keyof CreateTelemetryResponses];

export type DeleteRedirectData = {
    body?: never;
    path?: never;
    query: {
        id: number;
    };
    url: '/telemetry/redirect';
};

export type DeleteRedirectResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRedirectResponse = DeleteRedirectResponses[keyof DeleteRedirectResponses];

export type CreateRedirectData = {
    body?: never;
    path?: never;
    query: {
        id: number;
    };
    url: '/telemetry/redirect';
};

export type CreateRedirectResponses = {
    /**
     * OK
     */
    200: string;
};

export type CreateRedirectResponse = CreateRedirectResponses[keyof CreateRedirectResponses];

export type FindSponsorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sponsors';
};

export type FindSponsorsResponses = {
    /**
     * OK
     */
    200: Array<Sponsor>;
};

export type FindSponsorsResponse = FindSponsorsResponses[keyof FindSponsorsResponses];

export type CreateSponsorData = {
    body: Sponsor;
    path?: never;
    query?: never;
    url: '/sponsors';
};

export type CreateSponsorResponses = {
    /**
     * OK
     */
    200: Sponsor;
};

export type CreateSponsorResponse = CreateSponsorResponses[keyof CreateSponsorResponses];

export type FindMembershipsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/memberships';
};

export type FindMembershipsResponses = {
    /**
     * OK
     */
    200: Array<Membership>;
};

export type FindMembershipsResponse = FindMembershipsResponses[keyof FindMembershipsResponses];

export type CreateMembershipData = {
    body: Membership;
    path?: never;
    query?: never;
    url: '/memberships';
};

export type CreateMembershipResponses = {
    /**
     * OK
     */
    200: Membership;
};

export type CreateMembershipResponse = CreateMembershipResponses[keyof CreateMembershipResponses];

export type BoardCreateMembershipData = {
    body: Membership;
    path?: never;
    query?: never;
    url: '/memberships/member';
};

export type BoardCreateMembershipResponses = {
    /**
     * OK
     */
    200: Membership;
};

export type BoardCreateMembershipResponse = BoardCreateMembershipResponses[keyof BoardCreateMembershipResponses];

export type FindEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Zero-based page index (0..N)
         */
        page?: number;
        /**
         * The size of the page to be returned
         */
        size?: number;
        /**
         * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         */
        sort?: Array<string>;
        from?: string;
        to?: string;
        visible?: boolean;
        committeeId?: number;
        titleContains?: string;
    };
    url: '/events';
};

export type FindEventsResponses = {
    /**
     * OK
     */
    200: PageEvent;
};

export type FindEventsResponse = FindEventsResponses[keyof FindEventsResponses];

export type CreateEventData = {
    body: Event;
    path?: never;
    query?: never;
    url: '/events';
};

export type CreateEventResponses = {
    /**
     * OK
     */
    200: Event;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type CreateEventSignupData = {
    body: EventSignUp;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}/signups';
};

export type CreateEventSignupResponses = {
    /**
     * OK
     */
    200: EventSignUp;
};

export type CreateEventSignupResponse = CreateEventSignupResponses[keyof CreateEventSignupResponses];

export type FindContributionsData = {
    body?: never;
    path?: never;
    query?: {
        contributionPeriodId?: number;
    };
    url: '/contributions';
};

export type FindContributionsResponses = {
    /**
     * OK
     */
    200: Array<Contribution>;
};

export type FindContributionsResponse = FindContributionsResponses[keyof FindContributionsResponses];

export type CreateContributionData = {
    body: Contribution;
    path?: never;
    query?: never;
    url: '/contributions';
};

export type CreateContributionResponses = {
    /**
     * OK
     */
    200: Contribution;
};

export type CreateContributionResponse = CreateContributionResponses[keyof CreateContributionResponses];

export type FindContributionPeriodsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/contributionPeriods';
};

export type FindContributionPeriodsResponses = {
    /**
     * OK
     */
    200: Array<ContributionPeriod>;
};

export type FindContributionPeriodsResponse = FindContributionPeriodsResponses[keyof FindContributionPeriodsResponses];

export type CreateContributionPeriodData = {
    body: ContributionPeriod;
    path?: never;
    query?: never;
    url: '/contributionPeriods';
};

export type CreateContributionPeriodResponses = {
    /**
     * OK
     */
    200: ContributionPeriod;
};

export type CreateContributionPeriodResponse = CreateContributionPeriodResponses[keyof CreateContributionPeriodResponses];

export type FindCommitteesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/committees';
};

export type FindCommitteesResponses = {
    /**
     * OK
     */
    200: Array<BaseDto>;
};

export type FindCommitteesResponse = FindCommitteesResponses[keyof FindCommitteesResponses];

export type CreateCommitteeData = {
    body: AdvancedCommittee;
    path?: never;
    query?: never;
    url: '/committees';
};

export type CreateCommitteeResponses = {
    /**
     * OK
     */
    200: AdvancedCommittee;
};

export type CreateCommitteeResponse = CreateCommitteeResponses[keyof CreateCommitteeResponses];

export type FindBlogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/blogs';
};

export type FindBlogsResponses = {
    /**
     * OK
     */
    200: Array<Blog>;
};

export type FindBlogsResponse = FindBlogsResponses[keyof FindBlogsResponses];

export type CreateBlogData = {
    body: Blog;
    path?: never;
    query?: never;
    url: '/blogs';
};

export type CreateBlogResponses = {
    /**
     * OK
     */
    200: Blog;
};

export type CreateBlogResponse = CreateBlogResponses[keyof CreateBlogResponses];

export type DeleteByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/blogs/{id}';
};

export type DeleteByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteByIdResponse = DeleteByIdResponses[keyof DeleteByIdResponses];

export type FindBlogByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/blogs/{id}';
};

export type FindBlogByIdResponses = {
    /**
     * OK
     */
    200: Blog;
};

export type FindBlogByIdResponse = FindBlogByIdResponses[keyof FindBlogByIdResponses];

export type UpdateBlogData = {
    body: Blog;
    path: {
        id: number;
    };
    query?: never;
    url: '/blogs/{id}';
};

export type UpdateBlogResponses = {
    /**
     * OK
     */
    200: Blog;
};

export type UpdateBlogResponse = UpdateBlogResponses[keyof UpdateBlogResponses];

export type AuthenticateData = {
    body: JwtRequest;
    path?: never;
    query?: never;
    url: '/auth';
};

export type AuthenticateResponses = {
    /**
     * OK
     */
    200: Login;
};

export type AuthenticateResponse = AuthenticateResponses[keyof AuthenticateResponses];

export type UserActivateData = {
    body: UserActivationRequest;
    path?: never;
    query?: never;
    url: '/auth/user/activate';
};

export type UserActivateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ResetPasswordData = {
    body: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/auth/password/reset';
};

export type ResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MemberActivateData = {
    body: MemberActivationRequest;
    path?: never;
    query?: never;
    url: '/auth/member/activate';
};

export type MemberActivateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type FindAllAddressesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/addresses';
};

export type FindAllAddressesResponses = {
    /**
     * OK
     */
    200: Array<Address>;
};

export type FindAllAddressesResponse = FindAllAddressesResponses[keyof FindAllAddressesResponses];

export type CreateAddressData = {
    body: Address;
    path?: never;
    query?: never;
    url: '/addresses';
};

export type CreateAddressResponses = {
    /**
     * Created
     */
    201: Address;
};

export type CreateAddressResponse = CreateAddressResponses[keyof CreateAddressResponses];

export type DeleteUserByIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/users/{userId}';
};

export type DeleteUserByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteUserByIdResponse = DeleteUserByIdResponses[keyof DeleteUserByIdResponses];

export type FindUserByIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/users/{userId}';
};

export type FindUserByIdResponses = {
    /**
     * OK
     */
    200: AdvancedUser;
};

export type FindUserByIdResponse = FindUserByIdResponses[keyof FindUserByIdResponses];

export type DownloadProfilePictureData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/users/{userId}/profilePicture';
};

export type DownloadProfilePictureResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadProfilePictureResponse = DownloadProfilePictureResponses[keyof DownloadProfilePictureResponses];

export type FindTelemetryByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/telemetry/{id}';
};

export type FindTelemetryByIdResponses = {
    /**
     * OK
     */
    200: Telemetry;
};

export type FindTelemetryByIdResponse = FindTelemetryByIdResponses[keyof FindTelemetryByIdResponses];

export type FindRedirectsData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
    };
    url: '/telemetry/redirects';
};

export type FindRedirectsResponses = {
    /**
     * OK
     */
    200: Array<Redirect>;
};

export type FindRedirectsResponse = FindRedirectsResponses[keyof FindRedirectsResponses];

export type DownloadSignatureData = {
    body?: never;
    path: {
        membershipId: number;
    };
    query?: never;
    url: '/memberships/{membershipId}/signature';
};

export type DownloadSignatureResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadSignatureResponse = DownloadSignatureResponses[keyof DownloadSignatureResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type DownloadBannerData = {
    body?: never;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/events/{eventId}/banner';
};

export type DownloadBannerResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadBannerResponse = DownloadBannerResponses[keyof DownloadBannerResponses];

export type FindEventSignUpsForCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/events/signups';
};

export type FindEventSignUpsForCurrentUserResponses = {
    /**
     * OK
     */
    200: Array<EventSignUp>;
};

export type FindEventSignUpsForCurrentUserResponse = FindEventSignUpsForCurrentUserResponses[keyof FindEventSignUpsForCurrentUserResponses];

export type FindEventSignUpByAccessTokenData = {
    body?: never;
    path: {
        accessToken: string;
    };
    query?: never;
    url: '/events/signups/byAccessToken/{accessToken}';
};

export type FindEventSignUpByAccessTokenResponses = {
    /**
     * OK
     */
    200: EventSignUp;
};

export type FindEventSignUpByAccessTokenResponse = FindEventSignUpByAccessTokenResponses[keyof FindEventSignUpByAccessTokenResponses];

export type DownloadEventPictureData = {
    body?: never;
    path: {
        eventPictureId: number;
    };
    query?: never;
    url: '/eventPictures/{eventPictureId}';
};

export type DownloadEventPictureResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadEventPictureResponse = DownloadEventPictureResponses[keyof DownloadEventPictureResponses];

export type DownloadFileData = {
    body?: never;
    path: {
        filename: string;
    };
    query?: never;
    url: '/download/{filename}';
};

export type DownloadFileResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadFileResponse = DownloadFileResponses[keyof DownloadFileResponses];

export type FindContributionsByPeriodIdData = {
    body?: never;
    path: {
        periodId: number;
    };
    query?: never;
    url: '/contributionPeriods/{periodId}/contributions';
};

export type FindContributionsByPeriodIdResponses = {
    /**
     * OK
     */
    200: Array<Contribution>;
};

export type FindContributionsByPeriodIdResponse = FindContributionsByPeriodIdResponses[keyof FindContributionsByPeriodIdResponses];

export type FindCurrentContributionPeriodData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/contributionPeriods/current';
};

export type FindCurrentContributionPeriodResponses = {
    /**
     * OK
     */
    200: ContributionPeriod;
};

export type FindCurrentContributionPeriodResponse = FindCurrentContributionPeriodResponses[keyof FindCurrentContributionPeriodResponses];

export type FindCommitteeByIdData = {
    body?: never;
    path: {
        committeeId: number;
    };
    query?: never;
    url: '/committees/{committeeId}';
};

export type FindCommitteeByIdResponses = {
    /**
     * OK
     */
    200: BaseDto;
};

export type FindCommitteeByIdResponse = FindCommitteeByIdResponses[keyof FindCommitteeByIdResponses];

export type FindCommitteesForCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/committeeMembers/committees';
};

export type FindCommitteesForCurrentUserResponses = {
    /**
     * OK
     */
    200: Array<BaseDto>;
};

export type FindCommitteesForCurrentUserResponse = FindCommitteesForCurrentUserResponses[keyof FindCommitteesForCurrentUserResponses];

export type DownloadAssetData = {
    body?: never;
    path: {
        filename: string;
    };
    query?: never;
    url: '/assets/{filename}';
};

export type DownloadAssetResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadAssetResponse = DownloadAssetResponses[keyof DownloadAssetResponses];

export type DeleteEventByIdData = {
    body?: never;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/events/{eventId}';
};

export type DeleteEventByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteEventByIdResponse = DeleteEventByIdResponses[keyof DeleteEventByIdResponses];

export type DeleteEventSignupData = {
    body?: never;
    path: {
        eventSignupId: number;
    };
    query?: {
        accessToken?: string;
    };
    url: '/events/signups/{eventSignupId}';
};

export type DeleteEventSignupResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteEventSignupResponse = DeleteEventSignupResponses[keyof DeleteEventSignupResponses];

export type DeleteContributionData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/contributions/{id}';
};

export type DeleteContributionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteContributionResponse = DeleteContributionResponses[keyof DeleteContributionResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8080' | (string & {});
};
