spring:
  application:
    name: SocialMediaService

springdoc:
  api-docs:
    enabled: true

facebook:
  page:
    id: page
  access:
    token: 1234

x:
  api:
    key: smth
    secret: smth
  access:
    token: smth
    secret: smth