apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4.0.7-management
          ports:
            - containerPort: 5672
          env:
            - name: RABBITMQ_NODE_PORT
              value: "5672"
            - name: RABBITMQ_DEFAULT_USER
              value: "theuser"
            - name: RABBITMQ_DEFAULT_PASS
              value: "thepassword"
            - name: MYSQL_ROOT_PASSWORD
              value: "blueshell"
            - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
              value: "0"
            - name: MYSQL_DATABASE
              value: "blueshell"
            - name: MYSQL_HOST
              value: "db"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: "tim"
            - name: MYSQL_PASSWORD
              value: "blueshell"