import {fileURLToPath, URL} from "node:url"
import vue from "@vitejs/plugin-vue"
import {defineConfig} from "vitest/config"

export default defineConfig({
  plugins: [
    vue(),
  ],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  test: {
    environment: "jsdom",
    globals: true,
    // jsdom.ts first: it answers what the browser would before Vuetify, imported by
    // setup.ts, reads those answers once and caches them.
    setupFiles: ["./tests/jsdom.ts", "./tests/setup.ts"],
    include: ["tests/unit/**/*.test.ts"],
    exclude: ["tests/e2e/**"],
    css: true,
    server: {
      deps: {
        inline: ["vuetify"],
      },
    },
    clearMocks: true,
    restoreMocks: true,
    mockReset: true,
    coverage: {
      // istanbul, not v8, per ADR-005: v8 credits SFC branches it has no evidence
      // for, and the gate that ADR binds is read off the branch counter.
      provider: "istanbul",
      reportsDirectory: "./coverage/unit",
      reporter: ["text", "html", "lcov", "json", "json-summary"],
      include: ["src/**/*.{ts,vue}"],
      exclude: [
        "src/services/api/**",
        "src/main.ts",
      ],
      // Per-file, because there is no global gate and a project-wide number could
      // not fail for one new page anyway. Never lower a floor to make a build pass.
      thresholds: {
        perFile: true,
        "src/pages/activate/ActivateUser.vue": { lines: 90, branches: 90, functions: 100 },
        "src/pages/membership/MembershipSignUp.vue": { lines: 90, branches: 85, functions: 90 },
        "src/components/form/MembershipForm.vue": { lines: 90, branches: 85, functions: 90 },
        "src/components/form/AddressForm.vue": { lines: 79, branches: 45, functions: 60 },
        "src/domains/events/island/EventBand.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/events/island/EventSignUpPanel.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/events/island/AlsoComingUp.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/events/island/eventCalendar.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/events/island/useEventReader.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/pages/events/EventPage.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/form/EmailConfirmationPanel.vue": { lines: 90, branches: 90, functions: 90 },
        "src/components/island/PosterArt.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/events/island/AgendaRow.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/events/island/EventActions.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/events/island/EventAgenda.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/events/island/NextEventBand.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/events/island/eventFacts.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/pages/login/CreateAccount.vue": { lines: 90, branches: 85, functions: 85 },
        "src/domains/events/island/QuestionResponses.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/events/island/SignUpRoster.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/common/modals/RemoveSignUpDialog.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/common/modals/EditSignUpDialog.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/PosterStrip.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/association/adapters/association.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/discord/island/DiscordBand.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/discord/rooms.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/discord/island/VoicePeople.vue": { lines: 100, branches: 75, functions: 100, statements: 95 },
        "src/domains/association/island/EventsBand.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/association/island/useEventsOnShow.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },

        // The island's fields and the parts they are built from, which this branch wrote:
        // every line, every branch. A new one joins this list rather than lowering it.
        "src/components/island/BandRule.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/CallBand.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/CountryFlag.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/CountBadge.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/CheckBox.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/FormControl.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/CountryPicker.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/CutButton.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/DateInput.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/TimeInput.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/MoneyInput.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/FormField.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/FileInput.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/TextInput.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/MarkdownEditor.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/PhoneInput.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/SearchPicker.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/RadioGroup.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/TextArea.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/LeadBand.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/association/island/PartnerWall.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/association/island/PerkBand.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/association/island/homeBands.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/CountInput.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/DateTimeInput.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/IconButton.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/NoticeBox.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/useAnchoredPanel.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/association/island/CasualBand.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/association/island/casualGames.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/esports/island/LineupBand.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/esports/island/lineupSlice.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/BandHead.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/SocialMark.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/socialGlyphs.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/association/island/HomeHero.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/association/island/UpcomingBand.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/association/island/useUpcomingEvents.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/PanChevron.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/markdownEmoji.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/island/markdownLive.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/form/fields/CommitteePicker.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/domains/events/island/EventPreview.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/form/fields/CohortPicker.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/form/fields/ContributionPeriodPicker.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/form/fields/CountrySelect.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/form/fields/EnumPicker.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/form/fields/EventPicker.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/form/fields/MemberTypeSelect.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/form/fields/NationalitySelect.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/form/fields/QuestionEditor.vue": { lines: 100, branches: 85, functions: 100, statements: 98 },
        "src/components/form/SurveyForm.vue": { lines: 100, branches: 90, functions: 100, statements: 100 },
        "src/components/form/fields/UserPicker.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/form/fields/UserSelect.vue": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/form/fields/saidWrong.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/form/fields/fieldName.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/components/form/fields/userTerms.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/plugins/validation.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },

        // The forms these fields went into, held at what they cover today so a port cannot
        // quietly take a form backwards.
        "src/components/form/CommitteeForm.vue": { lines: 87, branches: 75, functions: 85 },
        "src/components/form/EventForm.vue": { lines: 50, branches: 42, functions: 52 },
        "src/components/form/GuestForm.vue": { lines: 77, branches: 100, functions: 66 },
        "src/components/form/UserForm.vue": { lines: 81, branches: 84, functions: 65 },
        "src/components/form/fields/VvField.vue": { lines: 83, branches: 57, functions: 75 },
        "src/components/island/Timeline.vue": { lines: 64, branches: 41, functions: 50 },
      },
    },
  },
})
