apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mariadb:10.11.10
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-env

          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: initdb
          configMap:
            name: mariadb-initdb