apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: utility-system
spec:
  interval: 24h
  url: https://headlamp-k8s.github.io/headlamp/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: utility-system
spec:
  interval: 10m
  chart:
    spec:
      chart: headlamp
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: utility-system
  values:
    config:
      oidc:
        clientID: headlamp
        issuerURL: https://auth.v2.esa-blueshell.nl
        scopes: openid,profile,email,groups
