server:
  port: 8080

blueshell:
  security:
    enabled: true

spring:
  mvc:
    dispatch-options-request: true
  rabbitmq:
    host: rabbitmq
    port: ${RABBITMQ_NODE_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}


app:
  url: ${APP_URL}

frontend:
  url: ${FRONTEND_URL}

communicators:
  api:
    port: 8080
    name: api
  apiGateway:
    port: 8080
    name: apigateway
  blogParser:
    port: 8080
    name: blogparser
  blogService:
    port: 8080
    name: blogservice
  emailParser:
    port: 8080
    name: emailparser
  eventParser:
    port: 8080
    name: eventparser
  fileService:
    port: 8080
    name: fileservice
  socialMediaService:
    port: 8080
    name: socialmediaservice
  telemetryService:
    port: 8080
    name: telemetry

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-server
    non-secure-port: 8080
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
