server:
  port: 8080

blueshell:
  identity:
    enabled: true

spring:
  mvc:
    dispatch-options-request: true
  cloud:
    stream:
      default-binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host:     rabbitmq
                port:     ${RABBITMQ_NODE_PORT}
                username: ${RABBITMQ_DEFAULT_USER}
                password: ${RABBITMQ_DEFAULT_PASS}

      bindings:
        asyncParseEmail-in-0:
          binder: rabbit
          destination: email-queue
          group: email-parser

        blog-out-0:
          binder: rabbit
          destination: blog-topic
          content-type: application/json

        asyncCreateBlog-in-0:
          binder: rabbit
          destination: blog-topic
          group: blog-service
          content-type: application/json

app:
  url: ${APP_URL}

frontend:
  url: ${FRONTEND_URL}


eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-server
    non-secure-port: 8080
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 60

logging:
  level:
    org:
      springframework:
        security: DEBUG