// This file is auto-generated by @hey-api/openapi-ts

export type AdvancedUserDto = SimpleUserDto & {
    initials: string;
    roles?: Array<'ANONYMOUS' | 'GUEST' | 'COMPANY' | 'MEMBER' | 'VEGAN' | 'COMMITTEE' | 'BOARD' | 'TREASURER' | 'ADMIN' | 'SYSTEM'>;
    dateOfBirth: string;
    phoneNumber: string;
    postalCode: string;
    address: string;
    city: string;
    country: string;
    nationality: string;
    signature: FileDto;
    membership?: MembershipDto;
    newsletter: boolean;
    photoConsent: boolean;
    ehbo: boolean;
    bhv: boolean;
    enabled?: boolean;
    incasso: boolean;
    createdAt?: string;
    gender?: string;
    study?: string;
    studentNumber?: string;
};

export type FileDto = {
    id?: number;
    name?: string;
    url?: string;
    uploaderId?: number;
    createdAt?: string;
    mediaType?: string;
    size?: number;
    fileName?: string;
    fileType?: 'DOCUMENT' | 'SIGNATURE' | 'PROFILE_PICTURE' | 'EVENT_BANNER' | 'EVENT_PICTURE' | 'SPONSOR_PICTURE';
    base64Content?: string;
};

export type MembershipDto = {
    id?: number;
    userId: number;
    memberType?: 'ALUMNI' | 'HONORARY' | 'REGULAR' | 'NONE';
    date?: string;
    city?: string;
    country?: string;
    signature?: FileDto;
    startDate?: string;
    endDate?: string;
};

export type SponsorDto = {
    id?: number;
    name: string;
    description: string;
};

export type EventDto = {
    id?: number;
    committeeId?: number;
    committee?: SimpleCommitteeDto;
    title: string;
    startTime: string;
    endTime: string;
    memberPrice?: string;
    publicPrice?: string;
    visible?: boolean;
    membersOnly?: boolean;
    signUp?: boolean;
    banner?: FileDto;
    signUpForm?: Array<FormQuestionDto>;
    description: string;
    location?: string;
};

export type FormQuestionDto = {
    prompt: string;
    type: string;
    options?: Array<string>;
};

export type SimpleCommitteeDto = {
    id?: number;
    name?: string;
    description?: string;
};

export type EventSignUpDto = {
    id?: number;
    eventId?: number;
    fullName?: string;
    discord?: string;
    email?: string;
    formAnswers?: Array<{
        [key: string]: unknown;
    }>;
};

export type ContributionDto = {
    id?: number;
    userId?: number;
    contributionPeriodId?: number;
    paid?: boolean;
    remindedAt?: string;
};

export type ContributionPeriodDto = {
    id?: number;
    startDate?: string;
    endDate?: string;
    halfYearFee?: number;
    fullYearFee?: number;
    alumniFee?: number;
    listId?: number;
};

export type AdvancedCommitteeDto = {
    id?: number;
    name: string;
    description?: string;
    members?: Array<CommitteeMemberDto>;
};

export type CommitteeMemberDto = {
    id?: number;
    role?: string;
    userId?: number;
    user?: SimpleUserDto | AdvancedUserDto;
    committeeId?: number;
};

export type SimpleUserDto = {
    id?: number;
    username?: string;
    discord?: string;
    firstName?: string;
    prefix?: string;
    lastName?: string;
    fullName?: string;
    email?: string;
};

export type BaseDto = {
    type: string;
};

export type PasswordResetRequest = {
    username: string;
    token: string;
    password: string;
};

export type ActivationRequest = {
    token: string;
    resetType: 'USER_ACTIVATION' | 'MEMBER_ACTIVATION' | 'PASSWORD_RESET';
    username?: string;
    password?: string;
};

export type TelemetryDto = {
    id?: string;
    url?: string;
    platform?: 'FACEBOOK' | 'LINKEDIN' | 'TWITTER' | 'INSTAGRAM';
    createdAt?: string;
};

export type BlogDto = {
    id?: string;
    url?: string;
    title?: string;
    text?: string;
    html?: string;
    markdown?: string;
    publishedAt?: string;
};

export type JwtRequest = {
    username?: string;
    password?: string;
};

export type JwtResponse = {
    token?: string;
    userId?: number;
    username?: string;
    expiration?: number;
    roles?: Array<string>;
};

export type RedirectDto = {
    id?: string;
    createdAt?: string;
    telemetry?: TelemetryDto;
};

export type Pageable = {
    page?: number;
    size?: number;
    sort?: Array<string>;
};

export type PageEventDto = {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<EventDto>;
    number?: number;
    sort?: SortObject;
    pageable?: PageableObject;
    numberOfElements?: number;
    first?: boolean;
    last?: boolean;
    empty?: boolean;
};

export type PageableObject = {
    offset?: number;
    sort?: SortObject;
    unpaged?: boolean;
    pageNumber?: number;
    paged?: boolean;
    pageSize?: number;
};

export type SortObject = {
    empty?: boolean;
    unsorted?: boolean;
    sorted?: boolean;
};

export type DeleteData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/users/{userId}';
};

export type DeleteResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteResponse = DeleteResponses[keyof DeleteResponses];

export type GetByIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/users/{userId}';
};

export type GetByIdResponses = {
    /**
     * OK
     */
    200: AdvancedUserDto;
};

export type GetByIdResponse = GetByIdResponses[keyof GetByIdResponses];

export type UpdateData = {
    body: AdvancedUserDto;
    path: {
        userId: number;
    };
    query?: never;
    url: '/users/{userId}';
};

export type UpdateResponses = {
    /**
     * OK
     */
    200: AdvancedUserDto;
};

export type UpdateResponse = UpdateResponses[keyof UpdateResponses];

export type ToggleRoleData = {
    body?: never;
    path: {
        userId: number;
    };
    query: {
        role: 'ANONYMOUS' | 'GUEST' | 'COMPANY' | 'MEMBER' | 'VEGAN' | 'COMMITTEE' | 'BOARD' | 'TREASURER' | 'ADMIN' | 'SYSTEM';
    };
    url: '/users/{userId}/roles';
};

export type ToggleRoleResponses = {
    /**
     * OK
     */
    200: AdvancedUserDto;
};

export type ToggleRoleResponse = ToggleRoleResponses[keyof ToggleRoleResponses];

export type UpdateMembershipData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        isMember?: boolean;
    };
    url: '/users/{id}/membership';
};

export type UpdateMembershipResponses = {
    /**
     * OK
     */
    200: AdvancedUserDto;
};

export type UpdateMembershipResponse = UpdateMembershipResponses[keyof UpdateMembershipResponses];

export type DeleteSponsorByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/sponsors/{id}';
};

export type DeleteSponsorByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSponsorByIdResponse = DeleteSponsorByIdResponses[keyof DeleteSponsorByIdResponses];

export type GetSponsorByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/sponsors/{id}';
};

export type GetSponsorByIdResponses = {
    /**
     * OK
     */
    200: SponsorDto;
};

export type GetSponsorByIdResponse = GetSponsorByIdResponses[keyof GetSponsorByIdResponses];

export type CreateOrUpdateSponsorData = {
    body: SponsorDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/sponsors/{id}';
};

export type CreateOrUpdateSponsorResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type CreateOrUpdateSponsorResponse = CreateOrUpdateSponsorResponses[keyof CreateOrUpdateSponsorResponses];

export type GetMembershipByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/memberships/{id}';
};

export type GetMembershipByIdResponses = {
    /**
     * OK
     */
    200: MembershipDto;
};

export type GetMembershipByIdResponse = GetMembershipByIdResponses[keyof GetMembershipByIdResponses];

export type UpdateMembership1Data = {
    body: MembershipDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/memberships/{id}';
};

export type UpdateMembership1Responses = {
    /**
     * OK
     */
    200: MembershipDto;
};

export type UpdateMembership1Response = UpdateMembership1Responses[keyof UpdateMembership1Responses];

export type DeleteEventByIdData = {
    body?: never;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/events/{eventId}';
};

export type DeleteEventByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteEventByIdResponse = DeleteEventByIdResponses[keyof DeleteEventByIdResponses];

export type UpdateEventData = {
    body: EventDto;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/events/{eventId}';
};

export type UpdateEventResponses = {
    /**
     * OK
     */
    200: EventDto;
};

export type UpdateEventResponse = UpdateEventResponses[keyof UpdateEventResponses];

export type UpdateSignUpData = {
    body: EventSignUpDto;
    path: {
        eventId: number;
    };
    query?: {
        accessToken?: string;
    };
    url: '/events/{eventId}/signups';
};

export type UpdateSignUpResponses = {
    /**
     * OK
     */
    200: EventSignUpDto;
};

export type UpdateSignUpResponse = UpdateSignUpResponses[keyof UpdateSignUpResponses];

export type PaidData = {
    body?: never;
    path: {
        id: number;
    };
    query: {
        paid: boolean;
    };
    url: '/contributions/{id}/paid';
};

export type PaidResponses = {
    /**
     * OK
     */
    200: ContributionDto;
};

export type PaidResponse = PaidResponses[keyof PaidResponses];

export type SendContributionReminderData = {
    body?: never;
    path: {
        periodId: number;
    };
    query?: never;
    url: '/contributionPeriods/{periodId}/contributions/remind';
};

export type SendContributionReminderResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteContributionPeriodData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/contributionPeriods/{id}';
};

export type DeleteContributionPeriodResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteContributionPeriodResponse = DeleteContributionPeriodResponses[keyof DeleteContributionPeriodResponses];

export type UpdateContributionPeriodData = {
    body: ContributionPeriodDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/contributionPeriods/{id}';
};

export type UpdateContributionPeriodResponses = {
    /**
     * OK
     */
    200: ContributionPeriodDto;
};

export type UpdateContributionPeriodResponse = UpdateContributionPeriodResponses[keyof UpdateContributionPeriodResponses];

export type DeleteCommitteeByIdData = {
    body?: never;
    path: {
        committeeId: number;
    };
    query?: never;
    url: '/committees/{committeeId}';
};

export type DeleteCommitteeByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteCommitteeByIdResponse = DeleteCommitteeByIdResponses[keyof DeleteCommitteeByIdResponses];

export type GetCommitteeByIdData = {
    body?: never;
    path: {
        committeeId: number;
    };
    query?: never;
    url: '/committees/{committeeId}';
};

export type GetCommitteeByIdResponses = {
    /**
     * OK
     */
    200: BaseDto;
};

export type GetCommitteeByIdResponse = GetCommitteeByIdResponses[keyof GetCommitteeByIdResponses];

export type UpdateCommitteeData = {
    body: AdvancedCommitteeDto;
    path: {
        committeeId: number;
    };
    query?: never;
    url: '/committees/{committeeId}';
};

export type UpdateCommitteeResponses = {
    /**
     * OK
     */
    200: BaseDto;
};

export type UpdateCommitteeResponse = UpdateCommitteeResponses[keyof UpdateCommitteeResponses];

export type GetAllData = {
    body?: never;
    path?: never;
    query: {
        isMember: boolean;
    };
    url: '/users';
};

export type GetAllResponses = {
    /**
     * OK
     */
    200: Array<AdvancedUserDto>;
};

export type GetAllResponse = GetAllResponses[keyof GetAllResponses];

export type CreateData = {
    body: AdvancedUserDto;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateResponses = {
    /**
     * OK
     */
    200: AdvancedUserDto;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type ResetPasswordData = {
    body?: never;
    path?: never;
    query: {
        username: string;
    };
    url: '/users/reset';
};

export type ResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type SetPasswordData = {
    body: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/users/password';
};

export type SetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ActivateData = {
    body: ActivationRequest;
    path?: never;
    query?: never;
    url: '/users/activate';
};

export type ActivateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CreateTelemetryData = {
    body?: never;
    path?: never;
    query: {
        platform: 'FACEBOOK' | 'LINKEDIN' | 'TWITTER' | 'INSTAGRAM';
        url: string;
    };
    url: '/telemetry';
};

export type CreateTelemetryResponses = {
    /**
     * OK
     */
    200: TelemetryDto;
};

export type CreateTelemetryResponse = CreateTelemetryResponses[keyof CreateTelemetryResponses];

export type DeleteRedirectData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/telemetry/redirect';
};

export type DeleteRedirectResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRedirectResponse = DeleteRedirectResponses[keyof DeleteRedirectResponses];

export type AddRedirectData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/telemetry/redirect';
};

export type AddRedirectResponses = {
    /**
     * OK
     */
    200: string;
};

export type AddRedirectResponse = AddRedirectResponses[keyof AddRedirectResponses];

export type GetSponsorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sponsors';
};

export type GetSponsorsResponses = {
    /**
     * OK
     */
    200: Array<SponsorDto>;
};

export type GetSponsorsResponse = GetSponsorsResponses[keyof GetSponsorsResponses];

export type CreateSponsorData = {
    body: SponsorDto;
    path?: never;
    query?: never;
    url: '/sponsors';
};

export type CreateSponsorResponses = {
    /**
     * OK
     */
    200: SponsorDto;
};

export type CreateSponsorResponse = CreateSponsorResponses[keyof CreateSponsorResponses];

export type GetMembershipsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/memberships';
};

export type GetMembershipsResponses = {
    /**
     * OK
     */
    200: Array<MembershipDto>;
};

export type GetMembershipsResponse = GetMembershipsResponses[keyof GetMembershipsResponses];

export type CreateMembershipData = {
    body: MembershipDto;
    path?: never;
    query?: never;
    url: '/memberships';
};

export type CreateMembershipResponses = {
    /**
     * OK
     */
    200: MembershipDto;
};

export type CreateMembershipResponse = CreateMembershipResponses[keyof CreateMembershipResponses];

export type GetEventsData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
    };
    url: '/events';
};

export type GetEventsResponses = {
    /**
     * OK
     */
    200: Array<EventDto>;
};

export type GetEventsResponse = GetEventsResponses[keyof GetEventsResponses];

export type CreateEventData = {
    body: EventDto;
    path?: never;
    query?: never;
    url: '/events';
};

export type CreateEventResponses = {
    /**
     * OK
     */
    200: EventDto;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type GetAllSignUpsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}/signups';
};

export type GetAllSignUpsResponses = {
    /**
     * OK
     */
    200: {
        parallel?: boolean;
    };
};

export type GetAllSignUpsResponse = GetAllSignUpsResponses[keyof GetAllSignUpsResponses];

export type CreateSignupData = {
    body: EventSignUpDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}/signups';
};

export type CreateSignupResponses = {
    /**
     * OK
     */
    200: EventSignUpDto;
};

export type CreateSignupResponse = CreateSignupResponses[keyof CreateSignupResponses];

export type GetAll1Data = {
    body?: never;
    path?: never;
    query?: {
        contributionPeriodId?: number;
    };
    url: '/contributions';
};

export type GetAll1Responses = {
    /**
     * OK
     */
    200: {
        parallel?: boolean;
    };
};

export type GetAll1Response = GetAll1Responses[keyof GetAll1Responses];

export type Create1Data = {
    body: ContributionDto;
    path?: never;
    query?: never;
    url: '/contributions';
};

export type Create1Responses = {
    /**
     * OK
     */
    200: ContributionDto;
};

export type Create1Response = Create1Responses[keyof Create1Responses];

export type GetContributionPeriodsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/contributionPeriods';
};

export type GetContributionPeriodsResponses = {
    /**
     * OK
     */
    200: Array<ContributionPeriodDto>;
};

export type GetContributionPeriodsResponse = GetContributionPeriodsResponses[keyof GetContributionPeriodsResponses];

export type CreateContributionPeriodData = {
    body: ContributionPeriodDto;
    path?: never;
    query?: never;
    url: '/contributionPeriods';
};

export type CreateContributionPeriodResponses = {
    /**
     * OK
     */
    200: ContributionPeriodDto;
};

export type CreateContributionPeriodResponse = CreateContributionPeriodResponses[keyof CreateContributionPeriodResponses];

export type GetCommitteesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/committees';
};

export type GetCommitteesResponses = {
    /**
     * OK
     */
    200: Array<BaseDto>;
};

export type GetCommitteesResponse = GetCommitteesResponses[keyof GetCommitteesResponses];

export type CreateCommitteeData = {
    body: AdvancedCommitteeDto;
    path?: never;
    query?: never;
    url: '/committees';
};

export type CreateCommitteeResponses = {
    /**
     * OK
     */
    200: AdvancedCommitteeDto;
};

export type CreateCommitteeResponse = CreateCommitteeResponses[keyof CreateCommitteeResponses];

export type FindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/blogs';
};

export type FindAllResponses = {
    /**
     * OK
     */
    200: Array<BlogDto>;
};

export type FindAllResponse = FindAllResponses[keyof FindAllResponses];

export type Create2Data = {
    body: BlogDto;
    path?: never;
    query?: never;
    url: '/blogs';
};

export type Create2Responses = {
    /**
     * OK
     */
    200: BlogDto;
};

export type Create2Response = Create2Responses[keyof Create2Responses];

export type AuthenticateData = {
    body: JwtRequest;
    path?: never;
    query?: never;
    url: '/auth';
};

export type AuthenticateResponses = {
    /**
     * OK
     */
    200: JwtResponse;
};

export type AuthenticateResponse = AuthenticateResponses[keyof AuthenticateResponses];

export type DownloadProfilePictureData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/users/{userId}/profilePicture';
};

export type DownloadProfilePictureResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadProfilePictureResponse = DownloadProfilePictureResponses[keyof DownloadProfilePictureResponses];

export type GetFromBrevoData = {
    body?: never;
    path?: never;
    query: {
        email: string;
    };
    url: '/users/brevo';
};

export type GetFromBrevoResponses = {
    /**
     * OK
     */
    200: AdvancedUserDto;
};

export type GetFromBrevoResponse = GetFromBrevoResponses[keyof GetFromBrevoResponses];

export type GetUpcomingEventsData = {
    body?: never;
    path?: never;
    query?: {
        editable?: boolean;
    };
    url: '/upcoming';
};

export type GetUpcomingEventsResponses = {
    /**
     * OK
     */
    200: Array<EventDto>;
};

export type GetUpcomingEventsResponse = GetUpcomingEventsResponses[keyof GetUpcomingEventsResponses];

export type GetTelemetryData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/telemetry/{id}';
};

export type GetTelemetryResponses = {
    /**
     * OK
     */
    200: TelemetryDto;
};

export type GetTelemetryResponse = GetTelemetryResponses[keyof GetTelemetryResponses];

export type GetRedirectsData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
    };
    url: '/telemetry/redirects';
};

export type GetRedirectsResponses = {
    /**
     * OK
     */
    200: Array<RedirectDto>;
};

export type GetRedirectsResponse = GetRedirectsResponses[keyof GetRedirectsResponses];

export type DownloadSignatureData = {
    body?: never;
    path: {
        membershipId: number;
    };
    query?: never;
    url: '/memberships/{membershipId}/signature';
};

export type DownloadSignatureResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadSignatureResponse = DownloadSignatureResponses[keyof DownloadSignatureResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type GetEventByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/events/{id}';
};

export type GetEventByIdResponses = {
    /**
     * OK
     */
    200: EventDto;
};

export type GetEventByIdResponse = GetEventByIdResponses[keyof GetEventByIdResponses];

export type DownloadBannerData = {
    body?: never;
    path: {
        eventId: number;
    };
    query?: never;
    url: '/events/{eventId}/banner';
};

export type DownloadBannerResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadBannerResponse = DownloadBannerResponses[keyof DownloadBannerResponses];

export type GetMySignUpsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/events/signups';
};

export type GetMySignUpsResponses = {
    /**
     * OK
     */
    200: Array<EventSignUpDto>;
};

export type GetMySignUpsResponse = GetMySignUpsResponses[keyof GetMySignUpsResponses];

export type GetSignUpByAccessTokenData = {
    body?: never;
    path: {
        accessToken: string;
    };
    query?: never;
    url: '/events/signups/byAccessToken/{accessToken}';
};

export type GetSignUpByAccessTokenResponses = {
    /**
     * OK
     */
    200: EventSignUpDto;
};

export type GetSignUpByAccessTokenResponse = GetSignUpByAccessTokenResponses[keyof GetSignUpByAccessTokenResponses];

export type GetPastEventsData = {
    body?: never;
    path?: never;
    query?: {
        editable?: boolean;
    };
    url: '/events/past';
};

export type GetPastEventsResponses = {
    /**
     * OK
     */
    200: {
        parallel?: boolean;
    };
};

export type GetPastEventsResponse = GetPastEventsResponses[keyof GetPastEventsResponses];

export type GetEventsPageableData = {
    body?: never;
    path?: never;
    query: {
        pageable: Pageable;
    };
    url: '/events/pageable';
};

export type GetEventsPageableResponses = {
    /**
     * OK
     */
    200: PageEventDto;
};

export type GetEventsPageableResponse = GetEventsPageableResponses[keyof GetEventsPageableResponses];

export type DownloadEventPictureData = {
    body?: never;
    path: {
        eventPictureId: number;
    };
    query?: never;
    url: '/eventPictures/{eventPictureId}';
};

export type DownloadEventPictureResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadEventPictureResponse = DownloadEventPictureResponses[keyof DownloadEventPictureResponses];

export type DownloadFileData = {
    body?: never;
    path: {
        filename: string;
    };
    query?: never;
    url: '/download/{filename}';
};

export type DownloadFileResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadFileResponse = DownloadFileResponses[keyof DownloadFileResponses];

export type GetContributionsByPeriodIdData = {
    body?: never;
    path: {
        periodId: number;
    };
    query?: never;
    url: '/contributionPeriods/{periodId}/contributions';
};

export type GetContributionsByPeriodIdResponses = {
    /**
     * OK
     */
    200: Array<ContributionDto>;
};

export type GetContributionsByPeriodIdResponse = GetContributionsByPeriodIdResponses[keyof GetContributionsByPeriodIdResponses];

export type GetCommitteesByUserIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/committeeMembers/committees';
};

export type GetCommitteesByUserIdResponses = {
    /**
     * OK
     */
    200: Array<BaseDto>;
};

export type GetCommitteesByUserIdResponse = GetCommitteesByUserIdResponses[keyof GetCommitteesByUserIdResponses];

export type DeleteByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/blogs/{id}';
};

export type DeleteByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteByIdResponse = DeleteByIdResponses[keyof DeleteByIdResponses];

export type FindByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/blogs/{id}';
};

export type FindByIdResponses = {
    /**
     * OK
     */
    200: BlogDto;
};

export type FindByIdResponse = FindByIdResponses[keyof FindByIdResponses];

export type DeleteSignupData = {
    body?: never;
    path: {
        eventSignupId: number;
    };
    query?: {
        accessToken?: string;
    };
    url: '/events/signups/{eventSignupId}';
};

export type DeleteSignupResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSignupResponse = DeleteSignupResponses[keyof DeleteSignupResponses];

export type Delete1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/contributions/{id}';
};

export type Delete1Responses = {
    /**
     * No Content
     */
    204: void;
};

export type Delete1Response = Delete1Responses[keyof Delete1Responses];

export type ClientOptions = {
    baseURL: 'http://localhost:8080' | (string & {});
};