# syntax=docker/dockerfile:1.7

FROM eclipse-temurin:24-jdk-alpine

WORKDIR /app

RUN apk add --no-cache curl

COPY gradlew gradlew
COPY gradle gradle
COPY settings.gradle.kts build.gradle.kts ./
COPY api api
COPY openapi openapi

RUN chmod +x gradlew
RUN --mount=type=cache,target=/root/.gradle ./gradlew --no-daemon :api:assemble -x test

EXPOSE ${PORT} 5005

CMD ["sh", "-c", "./gradlew --no-daemon :api:bootRun -Dspring-boot.run.profiles=dev -Dspring-boot.run.fork=false"]
