# syntax=docker/dockerfile:1.7

FROM maven:3.9.11-eclipse-temurin-24-alpine

COPY --from=root openapi /openapi

WORKDIR /app

COPY . .

RUN mvn install -am -DskipTests

EXPOSE ${PORT} 5005

CMD ["sh", "-c", "mvn spring-boot:run -Dspring-boot.run.profiles=dev -Dspring-boot.run.fork=false"]