name: Test API

on:
  push:
    paths: [ 'api/**' ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: api-ci-${{ github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      db:
        image: mariadb:10.11.10
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: "blueshell-test"
          MYSQL_DATABASE: "blueshell-test"
          MYSQL_PORT: 3306
          MYSQL_USER: "blueshell-test"
          MYSQL_PASSWORD: "blueshell-test"
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: "3306"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "blueshell-test"
      SPRING_PROFILES_ACTIVE: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24
          cache: maven

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Install Dependencies
        run: mvn install -q -DskipTests
        working-directory: api

      - name: Maven - clean verify
        run: mvn -B -DskipTests=false clean verify
        working-directory: api
