name: Build and Deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - 'core-commons/**'
      - 'db-commons/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-distribution: temurin
          java-version: 21
          maven-version: 3.9.9
          checkout-enabled: false

      - name: Publish core-commons package
        run: |
          cd core-commons
          mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}