openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://172.18.0.6:8080/event-parser
  description: Generated server url
paths:
  /queue:
    get:
      tags:
      - main-controller
      operationId: printQueue
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /health:
    get:
      tags:
      - main-controller
      operationId: healthCheck
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: boolean
components: {}
