openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://172.18.0.11:8080/files
  description: Generated server url
paths:
  /{filename}:
    get:
      tags:
      - file-controller
      operationId: downloadFile
      parameters:
      - name: filename
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: binary
  /health:
    get:
      tags:
      - main-controller
      operationId: healthCheck
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: boolean
components: {}
