openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://172.18.0.13:8080/social-media
  description: Generated server url
paths:
  /distribute:
    post:
      tags:
      - main-controller
      operationId: distributeEvent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SocialDTO'
        required: true
      responses:
        '200':
          description: OK
  /queue:
    get:
      tags:
      - main-controller
      operationId: printQueue
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /health:
    get:
      tags:
      - main-controller
      operationId: checkHealth
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: boolean
components:
  schemas:
    SocialDTO:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        text:
          type: string
        url:
          type: string
        platforms:
          type: array
          items:
            type: string
            enum:
            - FACEBOOK
            - LINKEDIN
            - TWITTER
            - INSTAGRAM
