openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://172.18.0.7:8080/telemetry
  description: Generated server url
paths:
  /telemetry:
    post:
      tags:
      - telemetry-controller
      operationId: createTelemetry
      parameters:
      - name: platform
        in: query
        required: true
        schema:
          type: string
          enum:
          - FACEBOOK
          - LINKEDIN
          - TWITTER
          - INSTAGRAM
      - name: url
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TelemetryDTO'
  /telemetry/{id}:
    get:
      tags:
      - telemetry-controller
      operationId: getTelemetry
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TelemetryDTO'
  /redirects:
    get:
      tags:
      - redirect-controller
      operationId: getRedirects
      parameters:
      - name: from
        in: query
        required: false
        schema:
          type: string
          format: date-time
      - name: to
        in: query
        required: false
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RedirectDTO'
  /health:
    get:
      tags:
      - main-controller
      operationId: checkHealth
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: boolean
  /redirect:
    get:
      tags:
      - redirect-controller
      operationId: redirect
      parameters:
      - name: telemetryId
        in: query
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    put:
      tags:
      - redirect-controller
      operationId: redirect_2
      parameters:
      - name: telemetryId
        in: query
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    post:
      tags:
      - redirect-controller
      operationId: redirect_1
      parameters:
      - name: telemetryId
        in: query
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    delete:
      tags:
      - redirect-controller
      operationId: redirect_3
      parameters:
      - name: telemetryId
        in: query
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    options:
      tags:
      - redirect-controller
      operationId: redirect_6
      parameters:
      - name: telemetryId
        in: query
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    head:
      tags:
      - redirect-controller
      operationId: redirect_5
      parameters:
      - name: telemetryId
        in: query
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    patch:
      tags:
      - redirect-controller
      operationId: redirect_4
      parameters:
      - name: telemetryId
        in: query
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    TelemetryDTO:
      type: object
      properties:
        id:
          type: string
        url:
          type: string
        platform:
          type: string
          enum:
          - FACEBOOK
          - LINKEDIN
          - TWITTER
          - INSTAGRAM
        createdAt:
          type: string
          format: date-time
    RedirectDTO:
      type: object
      properties:
        id:
          type: string
        created:
          type: string
          format: date-time
        telemetry:
          $ref: '#/components/schemas/TelemetryDTO'
